// ================================================================
// Auto-generated by CoreGen
// Generated at    : 2026-08-09 20:16:15
// Mode            : simu
// Git branch      : Dev_sys
// Git commit      : c54e60c
// Git message     : rm trash
// ================================================================

module CacheReplacer(
  input        clock,
  input        reset,
  input        io_touch_valid, // @[src/main/scala/frontend/icache/CacheReplacer.scala 19:14]
  input  [5:0] io_touch_idx, // @[src/main/scala/frontend/icache/CacheReplacer.scala 19:14]
  input  [1:0] io_touch_way, // @[src/main/scala/frontend/icache/CacheReplacer.scala 19:14]
  input        io_victim_req, // @[src/main/scala/frontend/icache/CacheReplacer.scala 19:14]
  input  [5:0] io_victim_idx, // @[src/main/scala/frontend/icache/CacheReplacer.scala 19:14]
  output [1:0] io_victim_resp // @[src/main/scala/frontend/icache/CacheReplacer.scala 19:14]
);
`ifdef RANDOMIZE_REG_INIT
  reg [31:0] _RAND_0;
  reg [31:0] _RAND_1;
  reg [31:0] _RAND_2;
  reg [31:0] _RAND_3;
  reg [31:0] _RAND_4;
  reg [31:0] _RAND_5;
  reg [31:0] _RAND_6;
  reg [31:0] _RAND_7;
  reg [31:0] _RAND_8;
  reg [31:0] _RAND_9;
  reg [31:0] _RAND_10;
  reg [31:0] _RAND_11;
  reg [31:0] _RAND_12;
  reg [31:0] _RAND_13;
  reg [31:0] _RAND_14;
  reg [31:0] _RAND_15;
  reg [31:0] _RAND_16;
  reg [31:0] _RAND_17;
  reg [31:0] _RAND_18;
  reg [31:0] _RAND_19;
  reg [31:0] _RAND_20;
  reg [31:0] _RAND_21;
  reg [31:0] _RAND_22;
  reg [31:0] _RAND_23;
  reg [31:0] _RAND_24;
  reg [31:0] _RAND_25;
  reg [31:0] _RAND_26;
  reg [31:0] _RAND_27;
  reg [31:0] _RAND_28;
  reg [31:0] _RAND_29;
  reg [31:0] _RAND_30;
  reg [31:0] _RAND_31;
  reg [31:0] _RAND_32;
  reg [31:0] _RAND_33;
  reg [31:0] _RAND_34;
  reg [31:0] _RAND_35;
  reg [31:0] _RAND_36;
  reg [31:0] _RAND_37;
  reg [31:0] _RAND_38;
  reg [31:0] _RAND_39;
  reg [31:0] _RAND_40;
  reg [31:0] _RAND_41;
  reg [31:0] _RAND_42;
  reg [31:0] _RAND_43;
  reg [31:0] _RAND_44;
  reg [31:0] _RAND_45;
  reg [31:0] _RAND_46;
  reg [31:0] _RAND_47;
  reg [31:0] _RAND_48;
  reg [31:0] _RAND_49;
  reg [31:0] _RAND_50;
  reg [31:0] _RAND_51;
  reg [31:0] _RAND_52;
  reg [31:0] _RAND_53;
  reg [31:0] _RAND_54;
  reg [31:0] _RAND_55;
  reg [31:0] _RAND_56;
  reg [31:0] _RAND_57;
  reg [31:0] _RAND_58;
  reg [31:0] _RAND_59;
  reg [31:0] _RAND_60;
  reg [31:0] _RAND_61;
  reg [31:0] _RAND_62;
  reg [31:0] _RAND_63;
  reg [31:0] _RAND_64;
`endif // RANDOMIZE_REG_INIT
  reg [1:0] victimRespReg; // @[src/main/scala/frontend/icache/CacheReplacer.scala 29:30]
  reg [2:0] plruTree_0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_2; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_3; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_4; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_5; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_6; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_7; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_8; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_9; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_10; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_11; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_12; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_13; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_14; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_15; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_16; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_17; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_18; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_19; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_20; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_21; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_22; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_23; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_24; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_25; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_26; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_27; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_28; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_29; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_30; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_31; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_32; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_33; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_34; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_35; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_36; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_37; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_38; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_39; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_40; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_41; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_42; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_43; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_44; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_45; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_46; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_47; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_48; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_49; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_50; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_51; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_52; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_53; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_54; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_55; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_56; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_57; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_58; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_59; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_60; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_61; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_62; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  reg [2:0] plruTree_63; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
  wire [2:0] _GEN_1 = 6'h1 == io_touch_idx ? plruTree_1 : plruTree_0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_2 = 6'h2 == io_touch_idx ? plruTree_2 : _GEN_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_3 = 6'h3 == io_touch_idx ? plruTree_3 : _GEN_2; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_4 = 6'h4 == io_touch_idx ? plruTree_4 : _GEN_3; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_5 = 6'h5 == io_touch_idx ? plruTree_5 : _GEN_4; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_6 = 6'h6 == io_touch_idx ? plruTree_6 : _GEN_5; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_7 = 6'h7 == io_touch_idx ? plruTree_7 : _GEN_6; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_8 = 6'h8 == io_touch_idx ? plruTree_8 : _GEN_7; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_9 = 6'h9 == io_touch_idx ? plruTree_9 : _GEN_8; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_10 = 6'ha == io_touch_idx ? plruTree_10 : _GEN_9; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_11 = 6'hb == io_touch_idx ? plruTree_11 : _GEN_10; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_12 = 6'hc == io_touch_idx ? plruTree_12 : _GEN_11; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_13 = 6'hd == io_touch_idx ? plruTree_13 : _GEN_12; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_14 = 6'he == io_touch_idx ? plruTree_14 : _GEN_13; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_15 = 6'hf == io_touch_idx ? plruTree_15 : _GEN_14; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_16 = 6'h10 == io_touch_idx ? plruTree_16 : _GEN_15; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_17 = 6'h11 == io_touch_idx ? plruTree_17 : _GEN_16; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_18 = 6'h12 == io_touch_idx ? plruTree_18 : _GEN_17; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_19 = 6'h13 == io_touch_idx ? plruTree_19 : _GEN_18; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_20 = 6'h14 == io_touch_idx ? plruTree_20 : _GEN_19; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_21 = 6'h15 == io_touch_idx ? plruTree_21 : _GEN_20; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_22 = 6'h16 == io_touch_idx ? plruTree_22 : _GEN_21; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_23 = 6'h17 == io_touch_idx ? plruTree_23 : _GEN_22; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_24 = 6'h18 == io_touch_idx ? plruTree_24 : _GEN_23; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_25 = 6'h19 == io_touch_idx ? plruTree_25 : _GEN_24; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_26 = 6'h1a == io_touch_idx ? plruTree_26 : _GEN_25; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_27 = 6'h1b == io_touch_idx ? plruTree_27 : _GEN_26; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_28 = 6'h1c == io_touch_idx ? plruTree_28 : _GEN_27; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_29 = 6'h1d == io_touch_idx ? plruTree_29 : _GEN_28; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_30 = 6'h1e == io_touch_idx ? plruTree_30 : _GEN_29; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_31 = 6'h1f == io_touch_idx ? plruTree_31 : _GEN_30; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_32 = 6'h20 == io_touch_idx ? plruTree_32 : _GEN_31; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_33 = 6'h21 == io_touch_idx ? plruTree_33 : _GEN_32; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_34 = 6'h22 == io_touch_idx ? plruTree_34 : _GEN_33; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_35 = 6'h23 == io_touch_idx ? plruTree_35 : _GEN_34; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_36 = 6'h24 == io_touch_idx ? plruTree_36 : _GEN_35; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_37 = 6'h25 == io_touch_idx ? plruTree_37 : _GEN_36; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_38 = 6'h26 == io_touch_idx ? plruTree_38 : _GEN_37; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_39 = 6'h27 == io_touch_idx ? plruTree_39 : _GEN_38; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_40 = 6'h28 == io_touch_idx ? plruTree_40 : _GEN_39; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_41 = 6'h29 == io_touch_idx ? plruTree_41 : _GEN_40; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_42 = 6'h2a == io_touch_idx ? plruTree_42 : _GEN_41; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_43 = 6'h2b == io_touch_idx ? plruTree_43 : _GEN_42; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_44 = 6'h2c == io_touch_idx ? plruTree_44 : _GEN_43; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_45 = 6'h2d == io_touch_idx ? plruTree_45 : _GEN_44; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_46 = 6'h2e == io_touch_idx ? plruTree_46 : _GEN_45; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_47 = 6'h2f == io_touch_idx ? plruTree_47 : _GEN_46; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_48 = 6'h30 == io_touch_idx ? plruTree_48 : _GEN_47; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_49 = 6'h31 == io_touch_idx ? plruTree_49 : _GEN_48; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_50 = 6'h32 == io_touch_idx ? plruTree_50 : _GEN_49; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_51 = 6'h33 == io_touch_idx ? plruTree_51 : _GEN_50; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_52 = 6'h34 == io_touch_idx ? plruTree_52 : _GEN_51; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_53 = 6'h35 == io_touch_idx ? plruTree_53 : _GEN_52; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_54 = 6'h36 == io_touch_idx ? plruTree_54 : _GEN_53; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_55 = 6'h37 == io_touch_idx ? plruTree_55 : _GEN_54; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_56 = 6'h38 == io_touch_idx ? plruTree_56 : _GEN_55; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_57 = 6'h39 == io_touch_idx ? plruTree_57 : _GEN_56; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_58 = 6'h3a == io_touch_idx ? plruTree_58 : _GEN_57; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_59 = 6'h3b == io_touch_idx ? plruTree_59 : _GEN_58; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_60 = 6'h3c == io_touch_idx ? plruTree_60 : _GEN_59; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_61 = 6'h3d == io_touch_idx ? plruTree_61 : _GEN_60; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_62 = 6'h3e == io_touch_idx ? plruTree_62 : _GEN_61; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _GEN_63 = 6'h3f == io_touch_idx ? plruTree_63 : _GEN_62; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:{41,41}]
  wire [2:0] _plruTree_newPLRU_T_1 = {_GEN_63[2],1'h1,1'h1}; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:33]
  wire [2:0] _plruTree_newPLRU_T_3 = {_GEN_63[2],1'h0,1'h1}; // @[src/main/scala/frontend/icache/CacheReplacer.scala 78:33]
  wire [2:0] _plruTree_newPLRU_T_5 = {1'h1,_GEN_63[1],1'h0}; // @[src/main/scala/frontend/icache/CacheReplacer.scala 79:33]
  wire [2:0] _plruTree_newPLRU_T_7 = {1'h0,_GEN_63[1],1'h0}; // @[src/main/scala/frontend/icache/CacheReplacer.scala 80:33]
  wire [2:0] _GEN_64 = 2'h3 == io_touch_way ? _plruTree_newPLRU_T_7 : 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 75:15 76:19 80:27]
  wire [2:0] _GEN_65 = 2'h2 == io_touch_way ? _plruTree_newPLRU_T_5 : _GEN_64; // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19 79:27]
  wire [2:0] _GEN_66 = 2'h1 == io_touch_way ? _plruTree_newPLRU_T_3 : _GEN_65; // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19 78:27]
  wire [2:0] _GEN_197 = 6'h1 == io_victim_idx ? plruTree_1 : plruTree_0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_198 = 6'h2 == io_victim_idx ? plruTree_2 : _GEN_197; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_199 = 6'h3 == io_victim_idx ? plruTree_3 : _GEN_198; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_200 = 6'h4 == io_victim_idx ? plruTree_4 : _GEN_199; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_201 = 6'h5 == io_victim_idx ? plruTree_5 : _GEN_200; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_202 = 6'h6 == io_victim_idx ? plruTree_6 : _GEN_201; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_203 = 6'h7 == io_victim_idx ? plruTree_7 : _GEN_202; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_204 = 6'h8 == io_victim_idx ? plruTree_8 : _GEN_203; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_205 = 6'h9 == io_victim_idx ? plruTree_9 : _GEN_204; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_206 = 6'ha == io_victim_idx ? plruTree_10 : _GEN_205; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_207 = 6'hb == io_victim_idx ? plruTree_11 : _GEN_206; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_208 = 6'hc == io_victim_idx ? plruTree_12 : _GEN_207; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_209 = 6'hd == io_victim_idx ? plruTree_13 : _GEN_208; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_210 = 6'he == io_victim_idx ? plruTree_14 : _GEN_209; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_211 = 6'hf == io_victim_idx ? plruTree_15 : _GEN_210; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_212 = 6'h10 == io_victim_idx ? plruTree_16 : _GEN_211; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_213 = 6'h11 == io_victim_idx ? plruTree_17 : _GEN_212; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_214 = 6'h12 == io_victim_idx ? plruTree_18 : _GEN_213; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_215 = 6'h13 == io_victim_idx ? plruTree_19 : _GEN_214; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_216 = 6'h14 == io_victim_idx ? plruTree_20 : _GEN_215; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_217 = 6'h15 == io_victim_idx ? plruTree_21 : _GEN_216; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_218 = 6'h16 == io_victim_idx ? plruTree_22 : _GEN_217; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_219 = 6'h17 == io_victim_idx ? plruTree_23 : _GEN_218; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_220 = 6'h18 == io_victim_idx ? plruTree_24 : _GEN_219; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_221 = 6'h19 == io_victim_idx ? plruTree_25 : _GEN_220; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_222 = 6'h1a == io_victim_idx ? plruTree_26 : _GEN_221; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_223 = 6'h1b == io_victim_idx ? plruTree_27 : _GEN_222; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_224 = 6'h1c == io_victim_idx ? plruTree_28 : _GEN_223; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_225 = 6'h1d == io_victim_idx ? plruTree_29 : _GEN_224; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_226 = 6'h1e == io_victim_idx ? plruTree_30 : _GEN_225; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_227 = 6'h1f == io_victim_idx ? plruTree_31 : _GEN_226; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_228 = 6'h20 == io_victim_idx ? plruTree_32 : _GEN_227; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_229 = 6'h21 == io_victim_idx ? plruTree_33 : _GEN_228; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_230 = 6'h22 == io_victim_idx ? plruTree_34 : _GEN_229; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_231 = 6'h23 == io_victim_idx ? plruTree_35 : _GEN_230; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_232 = 6'h24 == io_victim_idx ? plruTree_36 : _GEN_231; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_233 = 6'h25 == io_victim_idx ? plruTree_37 : _GEN_232; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_234 = 6'h26 == io_victim_idx ? plruTree_38 : _GEN_233; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_235 = 6'h27 == io_victim_idx ? plruTree_39 : _GEN_234; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_236 = 6'h28 == io_victim_idx ? plruTree_40 : _GEN_235; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_237 = 6'h29 == io_victim_idx ? plruTree_41 : _GEN_236; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_238 = 6'h2a == io_victim_idx ? plruTree_42 : _GEN_237; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_239 = 6'h2b == io_victim_idx ? plruTree_43 : _GEN_238; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_240 = 6'h2c == io_victim_idx ? plruTree_44 : _GEN_239; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_241 = 6'h2d == io_victim_idx ? plruTree_45 : _GEN_240; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_242 = 6'h2e == io_victim_idx ? plruTree_46 : _GEN_241; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_243 = 6'h2f == io_victim_idx ? plruTree_47 : _GEN_242; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_244 = 6'h30 == io_victim_idx ? plruTree_48 : _GEN_243; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_245 = 6'h31 == io_victim_idx ? plruTree_49 : _GEN_244; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_246 = 6'h32 == io_victim_idx ? plruTree_50 : _GEN_245; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_247 = 6'h33 == io_victim_idx ? plruTree_51 : _GEN_246; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_248 = 6'h34 == io_victim_idx ? plruTree_52 : _GEN_247; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_249 = 6'h35 == io_victim_idx ? plruTree_53 : _GEN_248; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_250 = 6'h36 == io_victim_idx ? plruTree_54 : _GEN_249; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_251 = 6'h37 == io_victim_idx ? plruTree_55 : _GEN_250; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_252 = 6'h38 == io_victim_idx ? plruTree_56 : _GEN_251; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_253 = 6'h39 == io_victim_idx ? plruTree_57 : _GEN_252; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_254 = 6'h3a == io_victim_idx ? plruTree_58 : _GEN_253; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_255 = 6'h3b == io_victim_idx ? plruTree_59 : _GEN_254; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_256 = 6'h3c == io_victim_idx ? plruTree_60 : _GEN_255; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_257 = 6'h3d == io_victim_idx ? plruTree_61 : _GEN_256; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_258 = 6'h3e == io_victim_idx ? plruTree_62 : _GEN_257; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire [2:0] _GEN_259 = 6'h3f == io_victim_idx ? plruTree_63 : _GEN_258; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:{23,23}]
  wire  victimRespReg_plru0 = _GEN_259[0]; // @[src/main/scala/frontend/icache/CacheReplacer.scala 86:23]
  wire  victimRespReg_plru1 = _GEN_259[1]; // @[src/main/scala/frontend/icache/CacheReplacer.scala 87:23]
  wire  victimRespReg_plru2 = _GEN_259[2]; // @[src/main/scala/frontend/icache/CacheReplacer.scala 88:23]
  wire  _victimRespReg_T_2 = ~victimRespReg_plru1 ? 1'h0 : 1'h1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 89:22]
  assign io_victim_resp = victimRespReg; // @[src/main/scala/frontend/icache/CacheReplacer.scala 105:18]
  always @(posedge clock) begin
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 29:30]
      victimRespReg <= 2'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 29:30]
    end else if (io_victim_req) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 96:25]
      if (~victimRespReg_plru0) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 89:10]
        victimRespReg <= {{1'd0}, _victimRespReg_T_2};
      end else if (~victimRespReg_plru2) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 89:45]
        victimRespReg <= 2'h2;
      end else begin
        victimRespReg <= 2'h3;
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_0 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h0 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_0 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_0 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_1 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h1 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_1 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_1 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_2 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h2 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_2 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_2 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_3 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h3 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_3 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_3 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_4 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h4 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_4 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_4 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_5 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h5 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_5 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_5 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_6 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h6 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_6 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_6 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_7 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h7 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_7 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_7 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_8 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h8 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_8 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_8 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_9 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h9 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_9 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_9 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_10 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'ha == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_10 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_10 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_11 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'hb == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_11 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_11 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_12 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'hc == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_12 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_12 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_13 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'hd == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_13 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_13 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_14 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'he == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_14 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_14 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_15 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'hf == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_15 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_15 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_16 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h10 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_16 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_16 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_17 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h11 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_17 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_17 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_18 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h12 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_18 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_18 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_19 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h13 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_19 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_19 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_20 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h14 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_20 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_20 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_21 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h15 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_21 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_21 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_22 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h16 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_22 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_22 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_23 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h17 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_23 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_23 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_24 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h18 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_24 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_24 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_25 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h19 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_25 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_25 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_26 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h1a == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_26 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_26 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_27 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h1b == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_27 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_27 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_28 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h1c == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_28 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_28 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_29 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h1d == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_29 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_29 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_30 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h1e == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_30 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_30 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_31 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h1f == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_31 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_31 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_32 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h20 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_32 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_32 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_33 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h21 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_33 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_33 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_34 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h22 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_34 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_34 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_35 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h23 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_35 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_35 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_36 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h24 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_36 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_36 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_37 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h25 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_37 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_37 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_38 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h26 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_38 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_38 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_39 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h27 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_39 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_39 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_40 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h28 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_40 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_40 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_41 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h29 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_41 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_41 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_42 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h2a == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_42 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_42 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_43 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h2b == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_43 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_43 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_44 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h2c == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_44 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_44 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_45 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h2d == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_45 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_45 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_46 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h2e == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_46 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_46 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_47 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h2f == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_47 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_47 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_48 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h30 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_48 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_48 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_49 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h31 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_49 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_49 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_50 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h32 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_50 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_50 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_51 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h33 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_51 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_51 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_52 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h34 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_52 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_52 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_53 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h35 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_53 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_53 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_54 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h36 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_54 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_54 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_55 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h37 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_55 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_55 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_56 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h38 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_56 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_56 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_57 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h39 == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_57 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_57 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_58 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h3a == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_58 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_58 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_59 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h3b == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_59 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_59 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_60 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h3c == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_60 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_60 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_61 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h3d == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_61 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_61 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_62 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h3e == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_62 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_62 <= _GEN_66;
        end
      end
    end
    if (reset) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
      plruTree_63 <= 3'h0; // @[src/main/scala/frontend/icache/CacheReplacer.scala 71:27]
    end else if (io_touch_valid) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 92:26]
      if (6'h3f == io_touch_idx) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 93:30]
        if (2'h0 == io_touch_way) begin // @[src/main/scala/frontend/icache/CacheReplacer.scala 76:19]
          plruTree_63 <= _plruTree_newPLRU_T_1; // @[src/main/scala/frontend/icache/CacheReplacer.scala 77:27]
        end else begin
          plruTree_63 <= _GEN_66;
        end
      end
    end
  end
// Register and memory initialization
`ifdef RANDOMIZE_GARBAGE_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_INVALID_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_REG_INIT
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_MEM_INIT
`define RANDOMIZE
`endif
`ifndef RANDOM
`define RANDOM $random
`endif
`ifdef RANDOMIZE_MEM_INIT
  integer initvar;
`endif
`ifndef SYNTHESIS
`ifdef FIRRTL_BEFORE_INITIAL
`FIRRTL_BEFORE_INITIAL
`endif
initial begin
  `ifdef RANDOMIZE
    `ifdef INIT_RANDOM
      `INIT_RANDOM
    `endif
    `ifndef VERILATOR
      `ifdef RANDOMIZE_DELAY
        #`RANDOMIZE_DELAY begin end
      `else
        #0.002 begin end
      `endif
    `endif
`ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {1{`RANDOM}};
  victimRespReg = _RAND_0[1:0];
  _RAND_1 = {1{`RANDOM}};
  plruTree_0 = _RAND_1[2:0];
  _RAND_2 = {1{`RANDOM}};
  plruTree_1 = _RAND_2[2:0];
  _RAND_3 = {1{`RANDOM}};
  plruTree_2 = _RAND_3[2:0];
  _RAND_4 = {1{`RANDOM}};
  plruTree_3 = _RAND_4[2:0];
  _RAND_5 = {1{`RANDOM}};
  plruTree_4 = _RAND_5[2:0];
  _RAND_6 = {1{`RANDOM}};
  plruTree_5 = _RAND_6[2:0];
  _RAND_7 = {1{`RANDOM}};
  plruTree_6 = _RAND_7[2:0];
  _RAND_8 = {1{`RANDOM}};
  plruTree_7 = _RAND_8[2:0];
  _RAND_9 = {1{`RANDOM}};
  plruTree_8 = _RAND_9[2:0];
  _RAND_10 = {1{`RANDOM}};
  plruTree_9 = _RAND_10[2:0];
  _RAND_11 = {1{`RANDOM}};
  plruTree_10 = _RAND_11[2:0];
  _RAND_12 = {1{`RANDOM}};
  plruTree_11 = _RAND_12[2:0];
  _RAND_13 = {1{`RANDOM}};
  plruTree_12 = _RAND_13[2:0];
  _RAND_14 = {1{`RANDOM}};
  plruTree_13 = _RAND_14[2:0];
  _RAND_15 = {1{`RANDOM}};
  plruTree_14 = _RAND_15[2:0];
  _RAND_16 = {1{`RANDOM}};
  plruTree_15 = _RAND_16[2:0];
  _RAND_17 = {1{`RANDOM}};
  plruTree_16 = _RAND_17[2:0];
  _RAND_18 = {1{`RANDOM}};
  plruTree_17 = _RAND_18[2:0];
  _RAND_19 = {1{`RANDOM}};
  plruTree_18 = _RAND_19[2:0];
  _RAND_20 = {1{`RANDOM}};
  plruTree_19 = _RAND_20[2:0];
  _RAND_21 = {1{`RANDOM}};
  plruTree_20 = _RAND_21[2:0];
  _RAND_22 = {1{`RANDOM}};
  plruTree_21 = _RAND_22[2:0];
  _RAND_23 = {1{`RANDOM}};
  plruTree_22 = _RAND_23[2:0];
  _RAND_24 = {1{`RANDOM}};
  plruTree_23 = _RAND_24[2:0];
  _RAND_25 = {1{`RANDOM}};
  plruTree_24 = _RAND_25[2:0];
  _RAND_26 = {1{`RANDOM}};
  plruTree_25 = _RAND_26[2:0];
  _RAND_27 = {1{`RANDOM}};
  plruTree_26 = _RAND_27[2:0];
  _RAND_28 = {1{`RANDOM}};
  plruTree_27 = _RAND_28[2:0];
  _RAND_29 = {1{`RANDOM}};
  plruTree_28 = _RAND_29[2:0];
  _RAND_30 = {1{`RANDOM}};
  plruTree_29 = _RAND_30[2:0];
  _RAND_31 = {1{`RANDOM}};
  plruTree_30 = _RAND_31[2:0];
  _RAND_32 = {1{`RANDOM}};
  plruTree_31 = _RAND_32[2:0];
  _RAND_33 = {1{`RANDOM}};
  plruTree_32 = _RAND_33[2:0];
  _RAND_34 = {1{`RANDOM}};
  plruTree_33 = _RAND_34[2:0];
  _RAND_35 = {1{`RANDOM}};
  plruTree_34 = _RAND_35[2:0];
  _RAND_36 = {1{`RANDOM}};
  plruTree_35 = _RAND_36[2:0];
  _RAND_37 = {1{`RANDOM}};
  plruTree_36 = _RAND_37[2:0];
  _RAND_38 = {1{`RANDOM}};
  plruTree_37 = _RAND_38[2:0];
  _RAND_39 = {1{`RANDOM}};
  plruTree_38 = _RAND_39[2:0];
  _RAND_40 = {1{`RANDOM}};
  plruTree_39 = _RAND_40[2:0];
  _RAND_41 = {1{`RANDOM}};
  plruTree_40 = _RAND_41[2:0];
  _RAND_42 = {1{`RANDOM}};
  plruTree_41 = _RAND_42[2:0];
  _RAND_43 = {1{`RANDOM}};
  plruTree_42 = _RAND_43[2:0];
  _RAND_44 = {1{`RANDOM}};
  plruTree_43 = _RAND_44[2:0];
  _RAND_45 = {1{`RANDOM}};
  plruTree_44 = _RAND_45[2:0];
  _RAND_46 = {1{`RANDOM}};
  plruTree_45 = _RAND_46[2:0];
  _RAND_47 = {1{`RANDOM}};
  plruTree_46 = _RAND_47[2:0];
  _RAND_48 = {1{`RANDOM}};
  plruTree_47 = _RAND_48[2:0];
  _RAND_49 = {1{`RANDOM}};
  plruTree_48 = _RAND_49[2:0];
  _RAND_50 = {1{`RANDOM}};
  plruTree_49 = _RAND_50[2:0];
  _RAND_51 = {1{`RANDOM}};
  plruTree_50 = _RAND_51[2:0];
  _RAND_52 = {1{`RANDOM}};
  plruTree_51 = _RAND_52[2:0];
  _RAND_53 = {1{`RANDOM}};
  plruTree_52 = _RAND_53[2:0];
  _RAND_54 = {1{`RANDOM}};
  plruTree_53 = _RAND_54[2:0];
  _RAND_55 = {1{`RANDOM}};
  plruTree_54 = _RAND_55[2:0];
  _RAND_56 = {1{`RANDOM}};
  plruTree_55 = _RAND_56[2:0];
  _RAND_57 = {1{`RANDOM}};
  plruTree_56 = _RAND_57[2:0];
  _RAND_58 = {1{`RANDOM}};
  plruTree_57 = _RAND_58[2:0];
  _RAND_59 = {1{`RANDOM}};
  plruTree_58 = _RAND_59[2:0];
  _RAND_60 = {1{`RANDOM}};
  plruTree_59 = _RAND_60[2:0];
  _RAND_61 = {1{`RANDOM}};
  plruTree_60 = _RAND_61[2:0];
  _RAND_62 = {1{`RANDOM}};
  plruTree_61 = _RAND_62[2:0];
  _RAND_63 = {1{`RANDOM}};
  plruTree_62 = _RAND_63[2:0];
  _RAND_64 = {1{`RANDOM}};
  plruTree_63 = _RAND_64[2:0];
`endif // RANDOMIZE_REG_INIT
  `endif // RANDOMIZE
end // initial
`ifdef FIRRTL_AFTER_INITIAL
`FIRRTL_AFTER_INITIAL
`endif
`endif // SYNTHESIS
endmodule
