// ================================================================
// Auto-generated by CoreGen
// Generated at    : 2026-08-09 20:16:15
// Mode            : simu
// Git branch      : Dev_sys
// Git commit      : c54e60c
// Git message     : rm trash
// ================================================================

module CSRUnit(
  input  [2:0]  io_uop_ctrl_csrOp, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  input         io_uop_ctrl_csrWen, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  input  [31:0] io_rs1, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  input  [31:0] io_rs2, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  input  [31:0] io_csrRdata, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  output [31:0] io_result, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  output        io_csrWen, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  output [31:0] io_csrWdata, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  input  [31:0] io_timerInfo_tid, // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
  input  [63:0] io_timerInfo_timer // @[src/main/scala/backend/execute/CSRUnit.scala 24:14]
);
  wire [31:0] cpuCfg_io_addr; // @[src/main/scala/backend/execute/CSRUnit.scala 40:22]
  wire [31:0] cpuCfg_io_rdata; // @[src/main/scala/backend/execute/CSRUnit.scala 40:22]
  wire [31:0] _csrNew_T = io_rs1 & io_rs2; // @[src/main/scala/backend/execute/CSRUnit.scala 57:29]
  wire [31:0] _csrNew_T_1 = ~io_rs1; // @[src/main/scala/backend/execute/CSRUnit.scala 57:51]
  wire [31:0] _csrNew_T_2 = io_csrRdata & _csrNew_T_1; // @[src/main/scala/backend/execute/CSRUnit.scala 57:49]
  wire [31:0] _csrNew_T_3 = _csrNew_T | _csrNew_T_2; // @[src/main/scala/backend/execute/CSRUnit.scala 57:39]
  wire [31:0] _csrNew_T_5 = 3'h2 == io_uop_ctrl_csrOp ? io_rs2 : io_csrRdata; // @[src/main/scala/backend/execute/CSRUnit.scala 55:37]
  wire [31:0] _io_result_T_3 = 3'h4 == io_uop_ctrl_csrOp ? io_timerInfo_timer[31:0] : io_csrRdata; // @[src/main/scala/backend/execute/CSRUnit.scala 63:37]
  wire [31:0] _io_result_T_5 = 3'h5 == io_uop_ctrl_csrOp ? io_timerInfo_timer[63:32] : _io_result_T_3; // @[src/main/scala/backend/execute/CSRUnit.scala 63:37]
  wire [31:0] _io_result_T_7 = 3'h6 == io_uop_ctrl_csrOp ? io_timerInfo_tid : _io_result_T_5; // @[src/main/scala/backend/execute/CSRUnit.scala 63:37]
  CpuCfg cpuCfg ( // @[src/main/scala/backend/execute/CSRUnit.scala 40:22]
    .io_addr(cpuCfg_io_addr),
    .io_rdata(cpuCfg_io_rdata)
  );
  assign io_result = 3'h7 == io_uop_ctrl_csrOp ? cpuCfg_io_rdata : _io_result_T_7; // @[src/main/scala/backend/execute/CSRUnit.scala 63:37]
  assign io_csrWen = io_uop_ctrl_csrWen; // @[src/main/scala/backend/execute/CSRUnit.scala 70:14]
  assign io_csrWdata = 3'h3 == io_uop_ctrl_csrOp ? _csrNew_T_3 : _csrNew_T_5; // @[src/main/scala/backend/execute/CSRUnit.scala 55:37]
  assign cpuCfg_io_addr = io_rs1; // @[src/main/scala/backend/execute/CSRUnit.scala 41:18]
endmodule
