// ================================================================
// Auto-generated by CoreGen
// Generated at    : 2026-08-09 20:16:15
// Mode            : simu
// Git branch      : Dev_sys
// Git commit      : c54e60c
// Git message     : rm trash
// ================================================================

module DCacheArray(
  input          clock,
  input          reset,
  input          io_read_valid, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [5:0]   io_read_idx, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_0_valid, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_0_dirty, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [19:0]  io_read_resp_ways_0_tag, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [511:0] io_read_resp_ways_0_data, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_1_valid, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_1_dirty, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [19:0]  io_read_resp_ways_1_tag, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [511:0] io_read_resp_ways_1_data, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_2_valid, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_2_dirty, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [19:0]  io_read_resp_ways_2_tag, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [511:0] io_read_resp_ways_2_data, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_3_valid, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_resp_ways_3_dirty, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [19:0]  io_read_resp_ways_3_tag, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [511:0] io_read_resp_ways_3_data, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_read_validOut, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input          io_write_valid, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [5:0]   io_write_idx, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [1:0]   io_write_way, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [19:0]  io_write_tag, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input          io_write_dirty, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [511:0] io_write_data, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input          io_metaWrite_valid, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [5:0]   io_metaWrite_idx, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [1:0]   io_metaWrite_way, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input  [19:0]  io_metaWrite_tag, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output         io_hasDirty, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [5:0]   io_dirtyIdx, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  output [1:0]   io_dirtyWay, // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
  input          io_dcacheInvalid // @[src/main/scala/memory/dcache/DCacheArray.scala 12:14]
);
`ifdef RANDOMIZE_REG_INIT
  reg [63:0] _RAND_0;
  reg [63:0] _RAND_1;
  reg [63:0] _RAND_2;
  reg [63:0] _RAND_3;
  reg [63:0] _RAND_4;
  reg [63:0] _RAND_5;
  reg [63:0] _RAND_6;
  reg [63:0] _RAND_7;
  reg [31:0] _RAND_8;
  reg [31:0] _RAND_9;
  reg [31:0] _RAND_10;
  reg [31:0] _RAND_11;
  reg [31:0] _RAND_12;
`endif // RANDOMIZE_REG_INIT
  wire  SimpleBlockRAM_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_1_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_1_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_1_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_1_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_1_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_1_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_1_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_1_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_2_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_2_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_2_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_2_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_2_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_2_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_2_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_2_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_3_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_3_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_3_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_3_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_3_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_3_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [5:0] SimpleBlockRAM_3_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire [20:0] SimpleBlockRAM_3_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
  wire  SimpleBlockRAM_4_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_4_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_4_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_4_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_4_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_4_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_4_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_4_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_5_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_5_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_5_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_5_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_5_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_5_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_5_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_5_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_6_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_6_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_6_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_6_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_6_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_6_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_6_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_6_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_7_clock; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_7_reset; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_7_io_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_7_io_wr_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_7_io_wr_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire  SimpleBlockRAM_7_io_rd_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [5:0] SimpleBlockRAM_7_io_rd_addr; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  wire [511:0] SimpleBlockRAM_7_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
  reg [63:0] validArray_0; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
  reg [63:0] validArray_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
  reg [63:0] validArray_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
  reg [63:0] validArray_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
  reg [63:0] dirtyArray_0; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
  reg [63:0] dirtyArray_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
  reg [63:0] dirtyArray_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
  reg [63:0] dirtyArray_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
  wire [3:0] dirtyWayMask = {|dirtyArray_3,|dirtyArray_2,|dirtyArray_1,|dirtyArray_0}; // @[src/main/scala/memory/dcache/DCacheArray.scala 46:79]
  wire [1:0] _io_dirtyWay_T_4 = dirtyWayMask[2] ? 2'h2 : 2'h3; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [1:0] _io_dirtyWay_T_5 = dirtyWayMask[1] ? 2'h1 : _io_dirtyWay_T_4; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [63:0] _GEN_1 = 2'h1 == io_dirtyWay ? dirtyArray_1 : dirtyArray_0; // @[src/main/scala/chisel3/util/OneHot.scala 48:{45,45}]
  wire [63:0] _GEN_2 = 2'h2 == io_dirtyWay ? dirtyArray_2 : _GEN_1; // @[src/main/scala/chisel3/util/OneHot.scala 48:{45,45}]
  wire [63:0] _GEN_3 = 2'h3 == io_dirtyWay ? dirtyArray_3 : _GEN_2; // @[src/main/scala/chisel3/util/OneHot.scala 48:{45,45}]
  wire [5:0] _io_dirtyIdx_T_64 = _GEN_3[62] ? 6'h3e : 6'h3f; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_65 = _GEN_3[61] ? 6'h3d : _io_dirtyIdx_T_64; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_66 = _GEN_3[60] ? 6'h3c : _io_dirtyIdx_T_65; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_67 = _GEN_3[59] ? 6'h3b : _io_dirtyIdx_T_66; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_68 = _GEN_3[58] ? 6'h3a : _io_dirtyIdx_T_67; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_69 = _GEN_3[57] ? 6'h39 : _io_dirtyIdx_T_68; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_70 = _GEN_3[56] ? 6'h38 : _io_dirtyIdx_T_69; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_71 = _GEN_3[55] ? 6'h37 : _io_dirtyIdx_T_70; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_72 = _GEN_3[54] ? 6'h36 : _io_dirtyIdx_T_71; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_73 = _GEN_3[53] ? 6'h35 : _io_dirtyIdx_T_72; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_74 = _GEN_3[52] ? 6'h34 : _io_dirtyIdx_T_73; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_75 = _GEN_3[51] ? 6'h33 : _io_dirtyIdx_T_74; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_76 = _GEN_3[50] ? 6'h32 : _io_dirtyIdx_T_75; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_77 = _GEN_3[49] ? 6'h31 : _io_dirtyIdx_T_76; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_78 = _GEN_3[48] ? 6'h30 : _io_dirtyIdx_T_77; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_79 = _GEN_3[47] ? 6'h2f : _io_dirtyIdx_T_78; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_80 = _GEN_3[46] ? 6'h2e : _io_dirtyIdx_T_79; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_81 = _GEN_3[45] ? 6'h2d : _io_dirtyIdx_T_80; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_82 = _GEN_3[44] ? 6'h2c : _io_dirtyIdx_T_81; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_83 = _GEN_3[43] ? 6'h2b : _io_dirtyIdx_T_82; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_84 = _GEN_3[42] ? 6'h2a : _io_dirtyIdx_T_83; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_85 = _GEN_3[41] ? 6'h29 : _io_dirtyIdx_T_84; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_86 = _GEN_3[40] ? 6'h28 : _io_dirtyIdx_T_85; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_87 = _GEN_3[39] ? 6'h27 : _io_dirtyIdx_T_86; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_88 = _GEN_3[38] ? 6'h26 : _io_dirtyIdx_T_87; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_89 = _GEN_3[37] ? 6'h25 : _io_dirtyIdx_T_88; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_90 = _GEN_3[36] ? 6'h24 : _io_dirtyIdx_T_89; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_91 = _GEN_3[35] ? 6'h23 : _io_dirtyIdx_T_90; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_92 = _GEN_3[34] ? 6'h22 : _io_dirtyIdx_T_91; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_93 = _GEN_3[33] ? 6'h21 : _io_dirtyIdx_T_92; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_94 = _GEN_3[32] ? 6'h20 : _io_dirtyIdx_T_93; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_95 = _GEN_3[31] ? 6'h1f : _io_dirtyIdx_T_94; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_96 = _GEN_3[30] ? 6'h1e : _io_dirtyIdx_T_95; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_97 = _GEN_3[29] ? 6'h1d : _io_dirtyIdx_T_96; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_98 = _GEN_3[28] ? 6'h1c : _io_dirtyIdx_T_97; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_99 = _GEN_3[27] ? 6'h1b : _io_dirtyIdx_T_98; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_100 = _GEN_3[26] ? 6'h1a : _io_dirtyIdx_T_99; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_101 = _GEN_3[25] ? 6'h19 : _io_dirtyIdx_T_100; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_102 = _GEN_3[24] ? 6'h18 : _io_dirtyIdx_T_101; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_103 = _GEN_3[23] ? 6'h17 : _io_dirtyIdx_T_102; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_104 = _GEN_3[22] ? 6'h16 : _io_dirtyIdx_T_103; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_105 = _GEN_3[21] ? 6'h15 : _io_dirtyIdx_T_104; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_106 = _GEN_3[20] ? 6'h14 : _io_dirtyIdx_T_105; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_107 = _GEN_3[19] ? 6'h13 : _io_dirtyIdx_T_106; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_108 = _GEN_3[18] ? 6'h12 : _io_dirtyIdx_T_107; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_109 = _GEN_3[17] ? 6'h11 : _io_dirtyIdx_T_108; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_110 = _GEN_3[16] ? 6'h10 : _io_dirtyIdx_T_109; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_111 = _GEN_3[15] ? 6'hf : _io_dirtyIdx_T_110; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_112 = _GEN_3[14] ? 6'he : _io_dirtyIdx_T_111; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_113 = _GEN_3[13] ? 6'hd : _io_dirtyIdx_T_112; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_114 = _GEN_3[12] ? 6'hc : _io_dirtyIdx_T_113; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_115 = _GEN_3[11] ? 6'hb : _io_dirtyIdx_T_114; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_116 = _GEN_3[10] ? 6'ha : _io_dirtyIdx_T_115; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_117 = _GEN_3[9] ? 6'h9 : _io_dirtyIdx_T_116; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_118 = _GEN_3[8] ? 6'h8 : _io_dirtyIdx_T_117; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_119 = _GEN_3[7] ? 6'h7 : _io_dirtyIdx_T_118; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_120 = _GEN_3[6] ? 6'h6 : _io_dirtyIdx_T_119; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_121 = _GEN_3[5] ? 6'h5 : _io_dirtyIdx_T_120; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_122 = _GEN_3[4] ? 6'h4 : _io_dirtyIdx_T_121; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_123 = _GEN_3[3] ? 6'h3 : _io_dirtyIdx_T_122; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_124 = _GEN_3[2] ? 6'h2 : _io_dirtyIdx_T_123; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [5:0] _io_dirtyIdx_T_125 = _GEN_3[1] ? 6'h1 : _io_dirtyIdx_T_124; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  reg [5:0] readIdxReg; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
  wire [63:0] _readRespData_ways_0_valid_T = validArray_0 >> readIdxReg; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire  readRespData_ways_0_valid = _readRespData_ways_0_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire [20:0] metaBRAMs_0_rd_data = SimpleBlockRAM_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:{26,26}]
  reg [5:0] readIdxReg_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
  wire [63:0] _readRespData_ways_1_valid_T = validArray_1 >> readIdxReg_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire  readRespData_ways_1_valid = _readRespData_ways_1_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire [20:0] metaBRAMs_1_rd_data = SimpleBlockRAM_1_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:{26,26}]
  reg [5:0] readIdxReg_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
  wire [63:0] _readRespData_ways_2_valid_T = validArray_2 >> readIdxReg_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire  readRespData_ways_2_valid = _readRespData_ways_2_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire [20:0] metaBRAMs_2_rd_data = SimpleBlockRAM_2_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:{26,26}]
  reg [5:0] readIdxReg_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
  wire [63:0] _readRespData_ways_3_valid_T = validArray_3 >> readIdxReg_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire  readRespData_ways_3_valid = _readRespData_ways_3_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  wire [20:0] metaBRAMs_3_rd_data = SimpleBlockRAM_3_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:{26,26}]
  reg  io_read_validOut_REG; // @[src/main/scala/memory/dcache/DCacheArray.scala 80:30]
  wire [3:0] writeWayOneHot = 4'h1 << io_write_way; // @[src/main/scala/chisel3/util/OneHot.scala 58:35]
  wire  waySel = writeWayOneHot[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 84:32]
  wire [20:0] metaWriteData = {io_write_dirty,io_write_tag}; // @[src/main/scala/memory/dcache/DCacheArray.scala 86:28]
  wire  dataBRAMs_0_wr_en = io_write_valid & waySel; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  wire [63:0] _validArray_0_T = 64'h1 << io_write_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _validArray_0_T_1 = validArray_0 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _validArray_0_T_2 = ~validArray_0; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _dirtyArray_0_T_1 = dirtyArray_0 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_0_T_2 = ~dirtyArray_0; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_0_T_3 = _dirtyArray_0_T_2 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_0_T_4 = ~_dirtyArray_0_T_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [5:0] _GEN_14 = dataBRAMs_0_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 88:28 93:36 98:30]
  wire [20:0] _GEN_15 = dataBRAMs_0_wr_en ? metaWriteData : 21'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 89:28 93:36 99:30]
  wire [3:0] _mwSel_T = 4'h1 << io_metaWrite_way; // @[src/main/scala/chisel3/util/OneHot.scala 58:35]
  wire  mwSel = _mwSel_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 106:43]
  wire [20:0] mwData = {1'h0,io_metaWrite_tag}; // @[src/main/scala/memory/dcache/DCacheArray.scala 109:23]
  wire [63:0] _validArray_0_T_6 = 64'h1 << io_metaWrite_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _validArray_0_T_9 = _validArray_0_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _validArray_0_T_10 = ~_validArray_0_T_9; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _dirtyArray_0_T_10 = _dirtyArray_0_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  wire [63:0] _dirtyArray_0_T_11 = ~_dirtyArray_0_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  wire  waySel_1 = writeWayOneHot[1]; // @[src/main/scala/memory/dcache/DCacheArray.scala 84:32]
  wire  dataBRAMs_1_wr_en = io_write_valid & waySel_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  wire [63:0] _validArray_1_T_1 = validArray_1 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _validArray_1_T_2 = ~validArray_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _dirtyArray_1_T_1 = dirtyArray_1 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_1_T_2 = ~dirtyArray_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_1_T_3 = _dirtyArray_1_T_2 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_1_T_4 = ~_dirtyArray_1_T_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [5:0] _GEN_27 = dataBRAMs_1_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 88:28 93:36 98:30]
  wire [20:0] _GEN_28 = dataBRAMs_1_wr_en ? metaWriteData : 21'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 89:28 93:36 99:30]
  wire  mwSel_1 = _mwSel_T[1]; // @[src/main/scala/memory/dcache/DCacheArray.scala 106:43]
  wire [63:0] _validArray_1_T_9 = _validArray_1_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _validArray_1_T_10 = ~_validArray_1_T_9; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _dirtyArray_1_T_10 = _dirtyArray_1_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  wire [63:0] _dirtyArray_1_T_11 = ~_dirtyArray_1_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  wire  waySel_2 = writeWayOneHot[2]; // @[src/main/scala/memory/dcache/DCacheArray.scala 84:32]
  wire  dataBRAMs_2_wr_en = io_write_valid & waySel_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  wire [63:0] _validArray_2_T_1 = validArray_2 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _validArray_2_T_2 = ~validArray_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _dirtyArray_2_T_1 = dirtyArray_2 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_2_T_2 = ~dirtyArray_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_2_T_3 = _dirtyArray_2_T_2 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_2_T_4 = ~_dirtyArray_2_T_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [5:0] _GEN_40 = dataBRAMs_2_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 88:28 93:36 98:30]
  wire [20:0] _GEN_41 = dataBRAMs_2_wr_en ? metaWriteData : 21'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 89:28 93:36 99:30]
  wire  mwSel_2 = _mwSel_T[2]; // @[src/main/scala/memory/dcache/DCacheArray.scala 106:43]
  wire [63:0] _validArray_2_T_9 = _validArray_2_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _validArray_2_T_10 = ~_validArray_2_T_9; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _dirtyArray_2_T_10 = _dirtyArray_2_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  wire [63:0] _dirtyArray_2_T_11 = ~_dirtyArray_2_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  wire  waySel_3 = writeWayOneHot[3]; // @[src/main/scala/memory/dcache/DCacheArray.scala 84:32]
  wire  dataBRAMs_3_wr_en = io_write_valid & waySel_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  wire [63:0] _validArray_3_T_1 = validArray_3 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _validArray_3_T_2 = ~validArray_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:48]
  wire [63:0] _dirtyArray_3_T_1 = dirtyArray_3 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_3_T_2 = ~dirtyArray_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_3_T_3 = _dirtyArray_3_T_2 | _validArray_0_T; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [63:0] _dirtyArray_3_T_4 = ~_dirtyArray_3_T_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
  wire [5:0] _GEN_53 = dataBRAMs_3_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 88:28 93:36 98:30]
  wire [20:0] _GEN_54 = dataBRAMs_3_wr_en ? metaWriteData : 21'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 89:28 93:36 99:30]
  wire  mwSel_3 = _mwSel_T[3]; // @[src/main/scala/memory/dcache/DCacheArray.scala 106:43]
  wire [63:0] _validArray_3_T_9 = _validArray_3_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _validArray_3_T_10 = ~_validArray_3_T_9; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:48]
  wire [63:0] _dirtyArray_3_T_10 = _dirtyArray_3_T_2 | _validArray_0_T_6; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  wire [63:0] _dirtyArray_3_T_11 = ~_dirtyArray_3_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:48]
  SimpleBlockRAM_12 SimpleBlockRAM ( // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
    .clock(SimpleBlockRAM_clock),
    .reset(SimpleBlockRAM_reset),
    .io_wr_en(SimpleBlockRAM_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_io_wr_data),
    .io_rd_en(SimpleBlockRAM_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_io_rd_data)
  );
  SimpleBlockRAM_12 SimpleBlockRAM_1 ( // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
    .clock(SimpleBlockRAM_1_clock),
    .reset(SimpleBlockRAM_1_reset),
    .io_wr_en(SimpleBlockRAM_1_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_1_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_1_io_wr_data),
    .io_rd_en(SimpleBlockRAM_1_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_1_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_1_io_rd_data)
  );
  SimpleBlockRAM_12 SimpleBlockRAM_2 ( // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
    .clock(SimpleBlockRAM_2_clock),
    .reset(SimpleBlockRAM_2_reset),
    .io_wr_en(SimpleBlockRAM_2_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_2_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_2_io_wr_data),
    .io_rd_en(SimpleBlockRAM_2_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_2_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_2_io_rd_data)
  );
  SimpleBlockRAM_12 SimpleBlockRAM_3 ( // @[src/main/scala/memory/dcache/DCacheArray.scala 52:11]
    .clock(SimpleBlockRAM_3_clock),
    .reset(SimpleBlockRAM_3_reset),
    .io_wr_en(SimpleBlockRAM_3_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_3_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_3_io_wr_data),
    .io_rd_en(SimpleBlockRAM_3_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_3_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_3_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_4 ( // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
    .clock(SimpleBlockRAM_4_clock),
    .reset(SimpleBlockRAM_4_reset),
    .io_wr_en(SimpleBlockRAM_4_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_4_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_4_io_wr_data),
    .io_rd_en(SimpleBlockRAM_4_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_4_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_4_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_5 ( // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
    .clock(SimpleBlockRAM_5_clock),
    .reset(SimpleBlockRAM_5_reset),
    .io_wr_en(SimpleBlockRAM_5_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_5_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_5_io_wr_data),
    .io_rd_en(SimpleBlockRAM_5_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_5_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_5_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_6 ( // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
    .clock(SimpleBlockRAM_6_clock),
    .reset(SimpleBlockRAM_6_reset),
    .io_wr_en(SimpleBlockRAM_6_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_6_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_6_io_wr_data),
    .io_rd_en(SimpleBlockRAM_6_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_6_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_6_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_7 ( // @[src/main/scala/memory/dcache/DCacheArray.scala 55:11]
    .clock(SimpleBlockRAM_7_clock),
    .reset(SimpleBlockRAM_7_reset),
    .io_wr_en(SimpleBlockRAM_7_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_7_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_7_io_wr_data),
    .io_rd_en(SimpleBlockRAM_7_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_7_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_7_io_rd_data)
  );
  assign io_read_resp_ways_0_valid = _readRespData_ways_0_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  assign io_read_resp_ways_0_dirty = metaBRAMs_0_rd_data[20] & readRespData_ways_0_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 74:55]
  assign io_read_resp_ways_0_tag = metaBRAMs_0_rd_data[19:0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 75:45]
  assign io_read_resp_ways_0_data = SimpleBlockRAM_4_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:{26,26}]
  assign io_read_resp_ways_1_valid = _readRespData_ways_1_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  assign io_read_resp_ways_1_dirty = metaBRAMs_1_rd_data[20] & readRespData_ways_1_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 74:55]
  assign io_read_resp_ways_1_tag = metaBRAMs_1_rd_data[19:0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 75:45]
  assign io_read_resp_ways_1_data = SimpleBlockRAM_5_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:{26,26}]
  assign io_read_resp_ways_2_valid = _readRespData_ways_2_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  assign io_read_resp_ways_2_dirty = metaBRAMs_2_rd_data[20] & readRespData_ways_2_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 74:55]
  assign io_read_resp_ways_2_tag = metaBRAMs_2_rd_data[19:0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 75:45]
  assign io_read_resp_ways_2_data = SimpleBlockRAM_6_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:{26,26}]
  assign io_read_resp_ways_3_valid = _readRespData_ways_3_valid_T[0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 72:52]
  assign io_read_resp_ways_3_dirty = metaBRAMs_3_rd_data[20] & readRespData_ways_3_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 74:55]
  assign io_read_resp_ways_3_tag = metaBRAMs_3_rd_data[19:0]; // @[src/main/scala/memory/dcache/DCacheArray.scala 75:45]
  assign io_read_resp_ways_3_data = SimpleBlockRAM_7_io_rd_data; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:{26,26}]
  assign io_read_validOut = io_read_validOut_REG; // @[src/main/scala/memory/dcache/DCacheArray.scala 80:20]
  assign io_hasDirty = |dirtyWayMask; // @[src/main/scala/memory/dcache/DCacheArray.scala 47:31]
  assign io_dirtyIdx = _GEN_3[0] ? 6'h0 : _io_dirtyIdx_T_125; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  assign io_dirtyWay = dirtyWayMask[0] ? 2'h0 : _io_dirtyWay_T_5; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  assign SimpleBlockRAM_clock = clock;
  assign SimpleBlockRAM_reset = reset;
  assign SimpleBlockRAM_io_wr_en = io_metaWrite_valid & mwSel & ~dataBRAMs_0_wr_en | dataBRAMs_0_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 113:30]
  assign SimpleBlockRAM_io_wr_addr = io_metaWrite_valid & mwSel & ~dataBRAMs_0_wr_en ? io_metaWrite_idx : _GEN_14; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 114:30]
  assign SimpleBlockRAM_io_wr_data = io_metaWrite_valid & mwSel & ~dataBRAMs_0_wr_en ? mwData : _GEN_15; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 115:30]
  assign SimpleBlockRAM_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 59:28]
  assign SimpleBlockRAM_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 60:28]
  assign SimpleBlockRAM_1_clock = clock;
  assign SimpleBlockRAM_1_reset = reset;
  assign SimpleBlockRAM_1_io_wr_en = io_metaWrite_valid & mwSel_1 & ~dataBRAMs_1_wr_en | dataBRAMs_1_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 113:30]
  assign SimpleBlockRAM_1_io_wr_addr = io_metaWrite_valid & mwSel_1 & ~dataBRAMs_1_wr_en ? io_metaWrite_idx : _GEN_27; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 114:30]
  assign SimpleBlockRAM_1_io_wr_data = io_metaWrite_valid & mwSel_1 & ~dataBRAMs_1_wr_en ? mwData : _GEN_28; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 115:30]
  assign SimpleBlockRAM_1_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 59:28]
  assign SimpleBlockRAM_1_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 60:28]
  assign SimpleBlockRAM_2_clock = clock;
  assign SimpleBlockRAM_2_reset = reset;
  assign SimpleBlockRAM_2_io_wr_en = io_metaWrite_valid & mwSel_2 & ~dataBRAMs_2_wr_en | dataBRAMs_2_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 113:30]
  assign SimpleBlockRAM_2_io_wr_addr = io_metaWrite_valid & mwSel_2 & ~dataBRAMs_2_wr_en ? io_metaWrite_idx : _GEN_40; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 114:30]
  assign SimpleBlockRAM_2_io_wr_data = io_metaWrite_valid & mwSel_2 & ~dataBRAMs_2_wr_en ? mwData : _GEN_41; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 115:30]
  assign SimpleBlockRAM_2_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 59:28]
  assign SimpleBlockRAM_2_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 60:28]
  assign SimpleBlockRAM_3_clock = clock;
  assign SimpleBlockRAM_3_reset = reset;
  assign SimpleBlockRAM_3_io_wr_en = io_metaWrite_valid & mwSel_3 & ~dataBRAMs_3_wr_en | dataBRAMs_3_wr_en; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 113:30]
  assign SimpleBlockRAM_3_io_wr_addr = io_metaWrite_valid & mwSel_3 & ~dataBRAMs_3_wr_en ? io_metaWrite_idx : _GEN_53; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 114:30]
  assign SimpleBlockRAM_3_io_wr_data = io_metaWrite_valid & mwSel_3 & ~dataBRAMs_3_wr_en ? mwData : _GEN_54; // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70 115:30]
  assign SimpleBlockRAM_3_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 59:28]
  assign SimpleBlockRAM_3_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 51:26 60:28]
  assign SimpleBlockRAM_4_clock = clock;
  assign SimpleBlockRAM_4_reset = reset;
  assign SimpleBlockRAM_4_io_wr_en = io_write_valid & waySel; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  assign SimpleBlockRAM_4_io_wr_addr = dataBRAMs_0_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 91:28 93:36]
  assign SimpleBlockRAM_4_io_wr_data = dataBRAMs_0_wr_en ? io_write_data : 512'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 92:28 93:36]
  assign SimpleBlockRAM_4_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 61:28]
  assign SimpleBlockRAM_4_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 62:28]
  assign SimpleBlockRAM_5_clock = clock;
  assign SimpleBlockRAM_5_reset = reset;
  assign SimpleBlockRAM_5_io_wr_en = io_write_valid & waySel_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  assign SimpleBlockRAM_5_io_wr_addr = dataBRAMs_1_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 91:28 93:36]
  assign SimpleBlockRAM_5_io_wr_data = dataBRAMs_1_wr_en ? io_write_data : 512'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 92:28 93:36]
  assign SimpleBlockRAM_5_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 61:28]
  assign SimpleBlockRAM_5_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 62:28]
  assign SimpleBlockRAM_6_clock = clock;
  assign SimpleBlockRAM_6_reset = reset;
  assign SimpleBlockRAM_6_io_wr_en = io_write_valid & waySel_2; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  assign SimpleBlockRAM_6_io_wr_addr = dataBRAMs_2_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 91:28 93:36]
  assign SimpleBlockRAM_6_io_wr_data = dataBRAMs_2_wr_en ? io_write_data : 512'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 92:28 93:36]
  assign SimpleBlockRAM_6_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 61:28]
  assign SimpleBlockRAM_6_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 62:28]
  assign SimpleBlockRAM_7_clock = clock;
  assign SimpleBlockRAM_7_reset = reset;
  assign SimpleBlockRAM_7_io_wr_en = io_write_valid & waySel_3; // @[src/main/scala/memory/dcache/DCacheArray.scala 93:25]
  assign SimpleBlockRAM_7_io_wr_addr = dataBRAMs_3_wr_en ? io_write_idx : 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 91:28 93:36]
  assign SimpleBlockRAM_7_io_wr_data = dataBRAMs_3_wr_en ? io_write_data : 512'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 92:28 93:36]
  assign SimpleBlockRAM_7_io_rd_en = io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 61:28]
  assign SimpleBlockRAM_7_io_rd_addr = io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 54:26 62:28]
  always @(posedge clock) begin
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
      validArray_0 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
    end else if (io_dcacheInvalid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 121:28]
      validArray_0 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 123:23]
    end else if (io_metaWrite_valid & mwSel & ~dataBRAMs_0_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      validArray_0 <= _validArray_0_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:23]
    end else if (dataBRAMs_0_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      validArray_0 <= _validArray_0_T_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:23]
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
      validArray_1 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
    end else if (io_dcacheInvalid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 121:28]
      validArray_1 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 123:23]
    end else if (io_metaWrite_valid & mwSel_1 & ~dataBRAMs_1_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      validArray_1 <= _validArray_1_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:23]
    end else if (dataBRAMs_1_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      validArray_1 <= _validArray_1_T_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:23]
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
      validArray_2 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
    end else if (io_dcacheInvalid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 121:28]
      validArray_2 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 123:23]
    end else if (io_metaWrite_valid & mwSel_2 & ~dataBRAMs_2_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      validArray_2 <= _validArray_2_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:23]
    end else if (dataBRAMs_2_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      validArray_2 <= _validArray_2_T_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:23]
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
      validArray_3 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 43:27]
    end else if (io_dcacheInvalid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 121:28]
      validArray_3 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 123:23]
    end else if (io_metaWrite_valid & mwSel_3 & ~dataBRAMs_3_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      validArray_3 <= _validArray_3_T_10; // @[src/main/scala/memory/dcache/DCacheArray.scala 110:23]
    end else if (dataBRAMs_3_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      validArray_3 <= _validArray_3_T_1; // @[src/main/scala/memory/dcache/DCacheArray.scala 94:23]
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
      dirtyArray_0 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
    end else if (io_metaWrite_valid & mwSel & ~dataBRAMs_0_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      dirtyArray_0 <= _dirtyArray_0_T_11; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:23]
    end else if (dataBRAMs_0_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      if (io_write_dirty) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
        dirtyArray_0 <= _dirtyArray_0_T_1;
      end else begin
        dirtyArray_0 <= _dirtyArray_0_T_4;
      end
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
      dirtyArray_1 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
    end else if (io_metaWrite_valid & mwSel_1 & ~dataBRAMs_1_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      dirtyArray_1 <= _dirtyArray_1_T_11; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:23]
    end else if (dataBRAMs_1_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      if (io_write_dirty) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
        dirtyArray_1 <= _dirtyArray_1_T_1;
      end else begin
        dirtyArray_1 <= _dirtyArray_1_T_4;
      end
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
      dirtyArray_2 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
    end else if (io_metaWrite_valid & mwSel_2 & ~dataBRAMs_2_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      dirtyArray_2 <= _dirtyArray_2_T_11; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:23]
    end else if (dataBRAMs_2_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      if (io_write_dirty) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
        dirtyArray_2 <= _dirtyArray_2_T_1;
      end else begin
        dirtyArray_2 <= _dirtyArray_2_T_4;
      end
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
      dirtyArray_3 <= 64'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 44:27]
    end else if (io_metaWrite_valid & mwSel_3 & ~dataBRAMs_3_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 107:70]
      dirtyArray_3 <= _dirtyArray_3_T_11; // @[src/main/scala/memory/dcache/DCacheArray.scala 111:23]
    end else if (dataBRAMs_3_wr_en) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 93:36]
      if (io_write_dirty) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 95:48]
        dirtyArray_3 <= _dirtyArray_3_T_1;
      end else begin
        dirtyArray_3 <= _dirtyArray_3_T_4;
      end
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg <= 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end else if (io_read_valid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg <= io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg_1 <= 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end else if (io_read_valid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg_1 <= io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg_2 <= 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end else if (io_read_valid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg_2 <= io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end
    if (reset) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg_3 <= 6'h0; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end else if (io_read_valid) begin // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
      readIdxReg_3 <= io_read_idx; // @[src/main/scala/memory/dcache/DCacheArray.scala 70:31]
    end
    io_read_validOut_REG <= io_read_valid; // @[src/main/scala/memory/dcache/DCacheArray.scala 80:30]
  end
// Register and memory initialization
`ifdef RANDOMIZE_GARBAGE_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_INVALID_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_REG_INIT
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_MEM_INIT
`define RANDOMIZE
`endif
`ifndef RANDOM
`define RANDOM $random
`endif
`ifdef RANDOMIZE_MEM_INIT
  integer initvar;
`endif
`ifndef SYNTHESIS
`ifdef FIRRTL_BEFORE_INITIAL
`FIRRTL_BEFORE_INITIAL
`endif
initial begin
  `ifdef RANDOMIZE
    `ifdef INIT_RANDOM
      `INIT_RANDOM
    `endif
    `ifndef VERILATOR
      `ifdef RANDOMIZE_DELAY
        #`RANDOMIZE_DELAY begin end
      `else
        #0.002 begin end
      `endif
    `endif
`ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {2{`RANDOM}};
  validArray_0 = _RAND_0[63:0];
  _RAND_1 = {2{`RANDOM}};
  validArray_1 = _RAND_1[63:0];
  _RAND_2 = {2{`RANDOM}};
  validArray_2 = _RAND_2[63:0];
  _RAND_3 = {2{`RANDOM}};
  validArray_3 = _RAND_3[63:0];
  _RAND_4 = {2{`RANDOM}};
  dirtyArray_0 = _RAND_4[63:0];
  _RAND_5 = {2{`RANDOM}};
  dirtyArray_1 = _RAND_5[63:0];
  _RAND_6 = {2{`RANDOM}};
  dirtyArray_2 = _RAND_6[63:0];
  _RAND_7 = {2{`RANDOM}};
  dirtyArray_3 = _RAND_7[63:0];
  _RAND_8 = {1{`RANDOM}};
  readIdxReg = _RAND_8[5:0];
  _RAND_9 = {1{`RANDOM}};
  readIdxReg_1 = _RAND_9[5:0];
  _RAND_10 = {1{`RANDOM}};
  readIdxReg_2 = _RAND_10[5:0];
  _RAND_11 = {1{`RANDOM}};
  readIdxReg_3 = _RAND_11[5:0];
  _RAND_12 = {1{`RANDOM}};
  io_read_validOut_REG = _RAND_12[0:0];
`endif // RANDOMIZE_REG_INIT
  `endif // RANDOMIZE
end // initial
`ifdef FIRRTL_AFTER_INITIAL
`FIRRTL_AFTER_INITIAL
`endif
`endif // SYNTHESIS
endmodule
