// ================================================================
// Auto-generated by CoreGen
// Generated at    : 2026-08-09 20:16:15
// Mode            : simu
// Git branch      : Dev_sys
// Git commit      : c54e60c
// Git message     : rm trash
// ================================================================

module DispatchRobBuffer(
  input         clock,
  input         reset,
  input         io_enq_valid_0, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_valid_1, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_valid_2, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_validforPreg_0, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_validforPreg_1, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_validforPreg_2, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [31:0] io_enq_bits_0_pc, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [31:0] io_enq_bits_0_inst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [3:0]  io_enq_bits_0_fuType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [6:0]  io_enq_bits_0_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [6:0]  io_enq_bits_0_oldPdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [4:0]  io_enq_bits_0_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_memRead, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_memWrite, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_csrWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_0_csrOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [13:0] io_enq_bits_0_csrWaddr, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_0_tlbOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_isPriv, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_isIdle, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_waitStore, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_llbitSet, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_llbitClear, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_ibar, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_0_isCacop, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_0_cacopCacheType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [1:0]  io_enq_bits_0_cacopOperation, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [16:0] io_enq_bits_0_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [31:0] io_enq_bits_1_pc, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [31:0] io_enq_bits_1_inst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [3:0]  io_enq_bits_1_fuType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [6:0]  io_enq_bits_1_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [6:0]  io_enq_bits_1_oldPdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [4:0]  io_enq_bits_1_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_memRead, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_memWrite, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_csrWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_1_csrOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [13:0] io_enq_bits_1_csrWaddr, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_1_tlbOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_isPriv, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_isIdle, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_waitStore, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_llbitSet, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_llbitClear, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_ibar, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_1_isCacop, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_1_cacopCacheType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [1:0]  io_enq_bits_1_cacopOperation, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [16:0] io_enq_bits_1_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [31:0] io_enq_bits_2_pc, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [31:0] io_enq_bits_2_inst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [3:0]  io_enq_bits_2_fuType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [6:0]  io_enq_bits_2_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [6:0]  io_enq_bits_2_oldPdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [4:0]  io_enq_bits_2_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_memRead, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_memWrite, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_csrWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_2_csrOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [13:0] io_enq_bits_2_csrWaddr, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_2_tlbOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_isPriv, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_isIdle, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_waitStore, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_llbitSet, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_llbitClear, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_ibar, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_enq_bits_2_isCacop, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [2:0]  io_enq_bits_2_cacopCacheType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [1:0]  io_enq_bits_2_cacopOperation, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input  [16:0] io_enq_bits_2_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_valid_0, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_valid_1, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_valid_2, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_validforPreg_0, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_validforPreg_1, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_validforPreg_2, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [31:0] io_deq_bits_0_pc, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [31:0] io_deq_bits_0_inst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [3:0]  io_deq_bits_0_fuType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deq_bits_0_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deq_bits_0_oldPdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [4:0]  io_deq_bits_0_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_memRead, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_memWrite, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_csrWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_0_csrOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [13:0] io_deq_bits_0_csrWaddr, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_0_tlbOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_isPriv, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_isIdle, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_waitStore, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_llbitSet, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_llbitClear, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_ibar, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_0_isCacop, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_0_cacopCacheType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [1:0]  io_deq_bits_0_cacopOperation, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [16:0] io_deq_bits_0_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [31:0] io_deq_bits_1_pc, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [31:0] io_deq_bits_1_inst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [3:0]  io_deq_bits_1_fuType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deq_bits_1_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deq_bits_1_oldPdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [4:0]  io_deq_bits_1_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_memRead, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_memWrite, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_csrWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_1_csrOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [13:0] io_deq_bits_1_csrWaddr, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_1_tlbOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_isPriv, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_isIdle, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_waitStore, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_llbitSet, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_llbitClear, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_ibar, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_1_isCacop, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_1_cacopCacheType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [1:0]  io_deq_bits_1_cacopOperation, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [16:0] io_deq_bits_1_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [31:0] io_deq_bits_2_pc, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [31:0] io_deq_bits_2_inst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [3:0]  io_deq_bits_2_fuType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deq_bits_2_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deq_bits_2_oldPdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [4:0]  io_deq_bits_2_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_memRead, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_memWrite, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_csrWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_2_csrOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [13:0] io_deq_bits_2_csrWaddr, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_2_tlbOp, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_isPriv, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_isIdle, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_waitStore, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_llbitSet, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_llbitClear, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_ibar, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deq_bits_2_isCacop, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_deq_bits_2_cacopCacheType, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [1:0]  io_deq_bits_2_cacopOperation, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [16:0] io_deq_bits_2_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deqDisp2Rob_validforPreg_0, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deqDisp2Rob_validforPreg_1, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deqDisp2Rob_validforPreg_2, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deqDisp2Rob_bits_0_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [4:0]  io_deqDisp2Rob_bits_0_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deqDisp2Rob_bits_0_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deqDisp2Rob_bits_1_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [4:0]  io_deqDisp2Rob_bits_1_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deqDisp2Rob_bits_1_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [6:0]  io_deqDisp2Rob_bits_2_pdst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [4:0]  io_deqDisp2Rob_bits_2_ldst, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_deqDisp2Rob_bits_2_rfWen, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output [2:0]  io_inFlightToRename, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  output        io_empty, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_flush, // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
  input         io_pause // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 24:14]
);
`ifdef RANDOMIZE_REG_INIT
  reg [31:0] _RAND_0;
  reg [31:0] _RAND_1;
  reg [31:0] _RAND_2;
  reg [31:0] _RAND_3;
  reg [31:0] _RAND_4;
  reg [31:0] _RAND_5;
  reg [31:0] _RAND_6;
  reg [31:0] _RAND_7;
  reg [31:0] _RAND_8;
  reg [31:0] _RAND_9;
  reg [31:0] _RAND_10;
  reg [31:0] _RAND_11;
  reg [31:0] _RAND_12;
  reg [31:0] _RAND_13;
  reg [31:0] _RAND_14;
  reg [31:0] _RAND_15;
  reg [31:0] _RAND_16;
  reg [31:0] _RAND_17;
  reg [31:0] _RAND_18;
  reg [31:0] _RAND_19;
  reg [31:0] _RAND_20;
  reg [31:0] _RAND_21;
  reg [31:0] _RAND_22;
  reg [31:0] _RAND_23;
  reg [31:0] _RAND_24;
  reg [31:0] _RAND_25;
  reg [31:0] _RAND_26;
  reg [31:0] _RAND_27;
  reg [31:0] _RAND_28;
  reg [31:0] _RAND_29;
  reg [31:0] _RAND_30;
  reg [31:0] _RAND_31;
  reg [31:0] _RAND_32;
  reg [31:0] _RAND_33;
  reg [31:0] _RAND_34;
  reg [31:0] _RAND_35;
  reg [31:0] _RAND_36;
  reg [31:0] _RAND_37;
  reg [31:0] _RAND_38;
  reg [31:0] _RAND_39;
  reg [31:0] _RAND_40;
  reg [31:0] _RAND_41;
  reg [31:0] _RAND_42;
  reg [31:0] _RAND_43;
  reg [31:0] _RAND_44;
  reg [31:0] _RAND_45;
  reg [31:0] _RAND_46;
  reg [31:0] _RAND_47;
  reg [31:0] _RAND_48;
  reg [31:0] _RAND_49;
  reg [31:0] _RAND_50;
  reg [31:0] _RAND_51;
  reg [31:0] _RAND_52;
  reg [31:0] _RAND_53;
  reg [31:0] _RAND_54;
  reg [31:0] _RAND_55;
  reg [31:0] _RAND_56;
  reg [31:0] _RAND_57;
  reg [31:0] _RAND_58;
  reg [31:0] _RAND_59;
  reg [31:0] _RAND_60;
  reg [31:0] _RAND_61;
  reg [31:0] _RAND_62;
  reg [31:0] _RAND_63;
  reg [31:0] _RAND_64;
  reg [31:0] _RAND_65;
  reg [31:0] _RAND_66;
  reg [31:0] _RAND_67;
  reg [31:0] _RAND_68;
  reg [31:0] _RAND_69;
  reg [31:0] _RAND_70;
  reg [31:0] _RAND_71;
  reg [31:0] _RAND_72;
  reg [31:0] _RAND_73;
  reg [31:0] _RAND_74;
  reg [31:0] _RAND_75;
  reg [31:0] _RAND_76;
  reg [31:0] _RAND_77;
`endif // RANDOMIZE_REG_INIT
  reg  bufValid_0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
  reg  bufValid_1; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
  reg  bufValid_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
  reg  bufValidForPreg_0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
  reg  bufValidForPreg_1; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
  reg  bufValidForPreg_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
  reg [31:0] bufData_0_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [31:0] bufData_0_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [3:0] bufData_0_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [6:0] bufData_0_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [6:0] bufData_0_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [4:0] bufData_0_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_0_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [13:0] bufData_0_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_0_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_0_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_0_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [1:0] bufData_0_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [16:0] bufData_0_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [31:0] bufData_1_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [31:0] bufData_1_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [3:0] bufData_1_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [6:0] bufData_1_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [6:0] bufData_1_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [4:0] bufData_1_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_1_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [13:0] bufData_1_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_1_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_1_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_1_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [1:0] bufData_1_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [16:0] bufData_1_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [31:0] bufData_2_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [31:0] bufData_2_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [3:0] bufData_2_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [6:0] bufData_2_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [6:0] bufData_2_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [4:0] bufData_2_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_2_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [13:0] bufData_2_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_2_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg  bufData_2_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [2:0] bufData_2_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [1:0] bufData_2_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  reg [16:0] bufData_2_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
  wire [2:0] _enqFire_T = {io_enq_valid_2,io_enq_valid_1,io_enq_valid_0}; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 54:30]
  wire  enqFire = |_enqFire_T; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 54:37]
  wire [2:0] _deqFire_T = {bufValid_2,bufValid_1,bufValid_0}; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 75:26]
  wire  _deqFire_T_1 = |_deqFire_T; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 75:33]
  wire  deqFire = |_deqFire_T & ~io_pause & ~io_flush; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 75:50]
  wire [1:0] _enqValidCount_T = io_enq_valid_1 + io_enq_valid_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 95:31]
  wire [1:0] _GEN_252 = {{1'd0}, io_enq_valid_0}; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 95:31]
  wire [2:0] _enqValidCount_T_2 = _GEN_252 + _enqValidCount_T; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 95:31]
  wire [1:0] enqValidCount = _enqValidCount_T_2[1:0]; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 95:31]
  wire [1:0] _bufValidCount_T = bufValid_1 + bufValid_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 96:31]
  wire [1:0] _GEN_253 = {{1'd0}, bufValid_0}; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 96:31]
  wire [2:0] _bufValidCount_T_2 = _GEN_253 + _bufValidCount_T; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 96:31]
  wire [1:0] bufValidCount = _bufValidCount_T_2[1:0]; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 96:31]
  assign io_deq_valid_0 = bufValid_0 & deqFire; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 78:37]
  assign io_deq_valid_1 = bufValid_1 & deqFire; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 78:37]
  assign io_deq_valid_2 = bufValid_2 & deqFire; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 78:37]
  assign io_deq_validforPreg_0 = bufValidForPreg_0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 81:28]
  assign io_deq_validforPreg_1 = bufValidForPreg_1; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 81:28]
  assign io_deq_validforPreg_2 = bufValidForPreg_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 81:28]
  assign io_deq_bits_0_pc = bufData_0_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_inst = bufData_0_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_fuType = bufData_0_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_pdst = bufData_0_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_oldPdst = bufData_0_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_ldst = bufData_0_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_rfWen = bufData_0_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_memRead = bufData_0_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_memWrite = bufData_0_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_csrWen = bufData_0_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_csrOp = bufData_0_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_csrWaddr = bufData_0_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_tlbOp = bufData_0_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_flushOnCommit = bufData_0_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_isPriv = bufData_0_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_isIdle = bufData_0_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_waitStore = bufData_0_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_llbitSet = bufData_0_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_llbitClear = bufData_0_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_ibar = bufData_0_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_isCacop = bufData_0_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_cacopCacheType = bufData_0_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_cacopOperation = bufData_0_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_0_excp_excpVec = bufData_0_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_pc = bufData_1_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_inst = bufData_1_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_fuType = bufData_1_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_pdst = bufData_1_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_oldPdst = bufData_1_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_ldst = bufData_1_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_rfWen = bufData_1_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_memRead = bufData_1_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_memWrite = bufData_1_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_csrWen = bufData_1_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_csrOp = bufData_1_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_csrWaddr = bufData_1_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_tlbOp = bufData_1_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_flushOnCommit = bufData_1_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_isPriv = bufData_1_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_isIdle = bufData_1_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_waitStore = bufData_1_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_llbitSet = bufData_1_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_llbitClear = bufData_1_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_ibar = bufData_1_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_isCacop = bufData_1_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_cacopCacheType = bufData_1_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_cacopOperation = bufData_1_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_1_excp_excpVec = bufData_1_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_pc = bufData_2_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_inst = bufData_2_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_fuType = bufData_2_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_pdst = bufData_2_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_oldPdst = bufData_2_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_ldst = bufData_2_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_rfWen = bufData_2_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_memRead = bufData_2_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_memWrite = bufData_2_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_csrWen = bufData_2_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_csrOp = bufData_2_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_csrWaddr = bufData_2_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_tlbOp = bufData_2_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_flushOnCommit = bufData_2_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_isPriv = bufData_2_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_isIdle = bufData_2_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_waitStore = bufData_2_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_llbitSet = bufData_2_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_llbitClear = bufData_2_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_ibar = bufData_2_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_isCacop = bufData_2_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_cacopCacheType = bufData_2_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_cacopOperation = bufData_2_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deq_bits_2_excp_excpVec = bufData_2_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 80:22]
  assign io_deqDisp2Rob_validforPreg_0 = io_enq_validforPreg_0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_validforPreg_1 = io_enq_validforPreg_1; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_validforPreg_2 = io_enq_validforPreg_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_0_pdst = io_enq_bits_0_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_0_ldst = io_enq_bits_0_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_0_rfWen = io_enq_bits_0_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_1_pdst = io_enq_bits_1_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_1_ldst = io_enq_bits_1_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_1_rfWen = io_enq_bits_1_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_2_pdst = io_enq_bits_2_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_2_ldst = io_enq_bits_2_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_deqDisp2Rob_bits_2_rfWen = io_enq_bits_2_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 41:18]
  assign io_inFlightToRename = enqValidCount + bufValidCount; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 99:40]
  assign io_empty = ~_deqFire_T_1; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 100:15]
  always @(posedge clock) begin
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
      bufValid_0 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
    end else if (deqFire & ~enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 85:29]
      bufValid_0 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 87:19]
    end else if (io_flush) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      bufValid_0 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 59:19]
    end else if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
      bufValid_0 <= io_enq_valid_0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 65:19]
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
      bufValid_1 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
    end else if (deqFire & ~enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 85:29]
      bufValid_1 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 87:19]
    end else if (io_flush) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      bufValid_1 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 59:19]
    end else if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
      bufValid_1 <= io_enq_valid_1; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 65:19]
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
      bufValid_2 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 46:26]
    end else if (deqFire & ~enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 85:29]
      bufValid_2 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 87:19]
    end else if (io_flush) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      bufValid_2 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 59:19]
    end else if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
      bufValid_2 <= io_enq_valid_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 65:19]
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
      bufValidForPreg_0 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
    end else if (deqFire & ~enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 85:29]
      bufValidForPreg_0 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 88:26]
    end else if (io_flush) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      bufValidForPreg_0 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 60:26]
    end else if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
      bufValidForPreg_0 <= io_enq_validforPreg_0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 66:26]
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
      bufValidForPreg_1 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
    end else if (deqFire & ~enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 85:29]
      bufValidForPreg_1 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 88:26]
    end else if (io_flush) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      bufValidForPreg_1 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 60:26]
    end else if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
      bufValidForPreg_1 <= io_enq_validforPreg_1; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 66:26]
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
      bufValidForPreg_2 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 47:33]
    end else if (deqFire & ~enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 85:29]
      bufValidForPreg_2 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 88:26]
    end else if (io_flush) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      bufValidForPreg_2 <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 60:26]
    end else if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
      bufValidForPreg_2 <= io_enq_validforPreg_2; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 66:26]
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_pc <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_pc <= io_enq_bits_0_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_inst <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_inst <= io_enq_bits_0_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_fuType <= 4'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_fuType <= io_enq_bits_0_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_pdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_pdst <= io_enq_bits_0_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_oldPdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_oldPdst <= io_enq_bits_0_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_ldst <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_ldst <= io_enq_bits_0_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_rfWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_rfWen <= io_enq_bits_0_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_memRead <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_memRead <= io_enq_bits_0_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_memWrite <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_memWrite <= io_enq_bits_0_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_csrWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_csrWen <= io_enq_bits_0_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_csrOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_csrOp <= io_enq_bits_0_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_csrWaddr <= 14'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_csrWaddr <= io_enq_bits_0_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_tlbOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_tlbOp <= io_enq_bits_0_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_flushOnCommit <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_flushOnCommit <= io_enq_bits_0_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_isPriv <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_isPriv <= io_enq_bits_0_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_isIdle <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_isIdle <= io_enq_bits_0_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_waitStore <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_waitStore <= io_enq_bits_0_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_llbitSet <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_llbitSet <= io_enq_bits_0_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_llbitClear <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_llbitClear <= io_enq_bits_0_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_ibar <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_ibar <= io_enq_bits_0_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_isCacop <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_isCacop <= io_enq_bits_0_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_cacopCacheType <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_cacopCacheType <= io_enq_bits_0_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_cacopOperation <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_cacopOperation <= io_enq_bits_0_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_0_excp_excpVec <= 17'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_0_excp_excpVec <= io_enq_bits_0_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_pc <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_pc <= io_enq_bits_1_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_inst <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_inst <= io_enq_bits_1_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_fuType <= 4'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_fuType <= io_enq_bits_1_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_pdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_pdst <= io_enq_bits_1_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_oldPdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_oldPdst <= io_enq_bits_1_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_ldst <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_ldst <= io_enq_bits_1_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_rfWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_rfWen <= io_enq_bits_1_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_memRead <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_memRead <= io_enq_bits_1_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_memWrite <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_memWrite <= io_enq_bits_1_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_csrWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_csrWen <= io_enq_bits_1_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_csrOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_csrOp <= io_enq_bits_1_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_csrWaddr <= 14'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_csrWaddr <= io_enq_bits_1_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_tlbOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_tlbOp <= io_enq_bits_1_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_flushOnCommit <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_flushOnCommit <= io_enq_bits_1_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_isPriv <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_isPriv <= io_enq_bits_1_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_isIdle <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_isIdle <= io_enq_bits_1_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_waitStore <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_waitStore <= io_enq_bits_1_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_llbitSet <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_llbitSet <= io_enq_bits_1_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_llbitClear <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_llbitClear <= io_enq_bits_1_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_ibar <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_ibar <= io_enq_bits_1_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_isCacop <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_isCacop <= io_enq_bits_1_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_cacopCacheType <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_cacopCacheType <= io_enq_bits_1_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_cacopOperation <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_cacopOperation <= io_enq_bits_1_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_1_excp_excpVec <= 17'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_1_excp_excpVec <= io_enq_bits_1_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_pc <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_pc <= io_enq_bits_2_pc; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_inst <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_inst <= io_enq_bits_2_inst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_fuType <= 4'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_fuType <= io_enq_bits_2_fuType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_pdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_pdst <= io_enq_bits_2_pdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_oldPdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_oldPdst <= io_enq_bits_2_oldPdst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_ldst <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_ldst <= io_enq_bits_2_ldst; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_rfWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_rfWen <= io_enq_bits_2_rfWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_memRead <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_memRead <= io_enq_bits_2_memRead; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_memWrite <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_memWrite <= io_enq_bits_2_memWrite; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_csrWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_csrWen <= io_enq_bits_2_csrWen; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_csrOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_csrOp <= io_enq_bits_2_csrOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_csrWaddr <= 14'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_csrWaddr <= io_enq_bits_2_csrWaddr; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_tlbOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_tlbOp <= io_enq_bits_2_tlbOp; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_flushOnCommit <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_flushOnCommit <= io_enq_bits_2_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_isPriv <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_isPriv <= io_enq_bits_2_isPriv; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_isIdle <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_isIdle <= io_enq_bits_2_isIdle; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_waitStore <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_waitStore <= io_enq_bits_2_waitStore; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_llbitSet <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_llbitSet <= io_enq_bits_2_llbitSet; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_llbitClear <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_llbitClear <= io_enq_bits_2_llbitClear; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_ibar <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_ibar <= io_enq_bits_2_ibar; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_isCacop <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_isCacop <= io_enq_bits_2_isCacop; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_cacopCacheType <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_cacopCacheType <= io_enq_bits_2_cacopCacheType; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_cacopOperation <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_cacopOperation <= io_enq_bits_2_cacopOperation; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
      bufData_2_excp_excpVec <= 17'h0; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 48:26]
    end else if (!(io_flush)) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 56:18]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 62:23]
        bufData_2_excp_excpVec <= io_enq_bits_2_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchRobBuffer.scala 67:19]
      end
    end
  end
// Register and memory initialization
`ifdef RANDOMIZE_GARBAGE_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_INVALID_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_REG_INIT
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_MEM_INIT
`define RANDOMIZE
`endif
`ifndef RANDOM
`define RANDOM $random
`endif
`ifdef RANDOMIZE_MEM_INIT
  integer initvar;
`endif
`ifndef SYNTHESIS
`ifdef FIRRTL_BEFORE_INITIAL
`FIRRTL_BEFORE_INITIAL
`endif
initial begin
  `ifdef RANDOMIZE
    `ifdef INIT_RANDOM
      `INIT_RANDOM
    `endif
    `ifndef VERILATOR
      `ifdef RANDOMIZE_DELAY
        #`RANDOMIZE_DELAY begin end
      `else
        #0.002 begin end
      `endif
    `endif
`ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {1{`RANDOM}};
  bufValid_0 = _RAND_0[0:0];
  _RAND_1 = {1{`RANDOM}};
  bufValid_1 = _RAND_1[0:0];
  _RAND_2 = {1{`RANDOM}};
  bufValid_2 = _RAND_2[0:0];
  _RAND_3 = {1{`RANDOM}};
  bufValidForPreg_0 = _RAND_3[0:0];
  _RAND_4 = {1{`RANDOM}};
  bufValidForPreg_1 = _RAND_4[0:0];
  _RAND_5 = {1{`RANDOM}};
  bufValidForPreg_2 = _RAND_5[0:0];
  _RAND_6 = {1{`RANDOM}};
  bufData_0_pc = _RAND_6[31:0];
  _RAND_7 = {1{`RANDOM}};
  bufData_0_inst = _RAND_7[31:0];
  _RAND_8 = {1{`RANDOM}};
  bufData_0_fuType = _RAND_8[3:0];
  _RAND_9 = {1{`RANDOM}};
  bufData_0_pdst = _RAND_9[6:0];
  _RAND_10 = {1{`RANDOM}};
  bufData_0_oldPdst = _RAND_10[6:0];
  _RAND_11 = {1{`RANDOM}};
  bufData_0_ldst = _RAND_11[4:0];
  _RAND_12 = {1{`RANDOM}};
  bufData_0_rfWen = _RAND_12[0:0];
  _RAND_13 = {1{`RANDOM}};
  bufData_0_memRead = _RAND_13[0:0];
  _RAND_14 = {1{`RANDOM}};
  bufData_0_memWrite = _RAND_14[0:0];
  _RAND_15 = {1{`RANDOM}};
  bufData_0_csrWen = _RAND_15[0:0];
  _RAND_16 = {1{`RANDOM}};
  bufData_0_csrOp = _RAND_16[2:0];
  _RAND_17 = {1{`RANDOM}};
  bufData_0_csrWaddr = _RAND_17[13:0];
  _RAND_18 = {1{`RANDOM}};
  bufData_0_tlbOp = _RAND_18[2:0];
  _RAND_19 = {1{`RANDOM}};
  bufData_0_flushOnCommit = _RAND_19[0:0];
  _RAND_20 = {1{`RANDOM}};
  bufData_0_isPriv = _RAND_20[0:0];
  _RAND_21 = {1{`RANDOM}};
  bufData_0_isIdle = _RAND_21[0:0];
  _RAND_22 = {1{`RANDOM}};
  bufData_0_waitStore = _RAND_22[0:0];
  _RAND_23 = {1{`RANDOM}};
  bufData_0_llbitSet = _RAND_23[0:0];
  _RAND_24 = {1{`RANDOM}};
  bufData_0_llbitClear = _RAND_24[0:0];
  _RAND_25 = {1{`RANDOM}};
  bufData_0_ibar = _RAND_25[0:0];
  _RAND_26 = {1{`RANDOM}};
  bufData_0_isCacop = _RAND_26[0:0];
  _RAND_27 = {1{`RANDOM}};
  bufData_0_cacopCacheType = _RAND_27[2:0];
  _RAND_28 = {1{`RANDOM}};
  bufData_0_cacopOperation = _RAND_28[1:0];
  _RAND_29 = {1{`RANDOM}};
  bufData_0_excp_excpVec = _RAND_29[16:0];
  _RAND_30 = {1{`RANDOM}};
  bufData_1_pc = _RAND_30[31:0];
  _RAND_31 = {1{`RANDOM}};
  bufData_1_inst = _RAND_31[31:0];
  _RAND_32 = {1{`RANDOM}};
  bufData_1_fuType = _RAND_32[3:0];
  _RAND_33 = {1{`RANDOM}};
  bufData_1_pdst = _RAND_33[6:0];
  _RAND_34 = {1{`RANDOM}};
  bufData_1_oldPdst = _RAND_34[6:0];
  _RAND_35 = {1{`RANDOM}};
  bufData_1_ldst = _RAND_35[4:0];
  _RAND_36 = {1{`RANDOM}};
  bufData_1_rfWen = _RAND_36[0:0];
  _RAND_37 = {1{`RANDOM}};
  bufData_1_memRead = _RAND_37[0:0];
  _RAND_38 = {1{`RANDOM}};
  bufData_1_memWrite = _RAND_38[0:0];
  _RAND_39 = {1{`RANDOM}};
  bufData_1_csrWen = _RAND_39[0:0];
  _RAND_40 = {1{`RANDOM}};
  bufData_1_csrOp = _RAND_40[2:0];
  _RAND_41 = {1{`RANDOM}};
  bufData_1_csrWaddr = _RAND_41[13:0];
  _RAND_42 = {1{`RANDOM}};
  bufData_1_tlbOp = _RAND_42[2:0];
  _RAND_43 = {1{`RANDOM}};
  bufData_1_flushOnCommit = _RAND_43[0:0];
  _RAND_44 = {1{`RANDOM}};
  bufData_1_isPriv = _RAND_44[0:0];
  _RAND_45 = {1{`RANDOM}};
  bufData_1_isIdle = _RAND_45[0:0];
  _RAND_46 = {1{`RANDOM}};
  bufData_1_waitStore = _RAND_46[0:0];
  _RAND_47 = {1{`RANDOM}};
  bufData_1_llbitSet = _RAND_47[0:0];
  _RAND_48 = {1{`RANDOM}};
  bufData_1_llbitClear = _RAND_48[0:0];
  _RAND_49 = {1{`RANDOM}};
  bufData_1_ibar = _RAND_49[0:0];
  _RAND_50 = {1{`RANDOM}};
  bufData_1_isCacop = _RAND_50[0:0];
  _RAND_51 = {1{`RANDOM}};
  bufData_1_cacopCacheType = _RAND_51[2:0];
  _RAND_52 = {1{`RANDOM}};
  bufData_1_cacopOperation = _RAND_52[1:0];
  _RAND_53 = {1{`RANDOM}};
  bufData_1_excp_excpVec = _RAND_53[16:0];
  _RAND_54 = {1{`RANDOM}};
  bufData_2_pc = _RAND_54[31:0];
  _RAND_55 = {1{`RANDOM}};
  bufData_2_inst = _RAND_55[31:0];
  _RAND_56 = {1{`RANDOM}};
  bufData_2_fuType = _RAND_56[3:0];
  _RAND_57 = {1{`RANDOM}};
  bufData_2_pdst = _RAND_57[6:0];
  _RAND_58 = {1{`RANDOM}};
  bufData_2_oldPdst = _RAND_58[6:0];
  _RAND_59 = {1{`RANDOM}};
  bufData_2_ldst = _RAND_59[4:0];
  _RAND_60 = {1{`RANDOM}};
  bufData_2_rfWen = _RAND_60[0:0];
  _RAND_61 = {1{`RANDOM}};
  bufData_2_memRead = _RAND_61[0:0];
  _RAND_62 = {1{`RANDOM}};
  bufData_2_memWrite = _RAND_62[0:0];
  _RAND_63 = {1{`RANDOM}};
  bufData_2_csrWen = _RAND_63[0:0];
  _RAND_64 = {1{`RANDOM}};
  bufData_2_csrOp = _RAND_64[2:0];
  _RAND_65 = {1{`RANDOM}};
  bufData_2_csrWaddr = _RAND_65[13:0];
  _RAND_66 = {1{`RANDOM}};
  bufData_2_tlbOp = _RAND_66[2:0];
  _RAND_67 = {1{`RANDOM}};
  bufData_2_flushOnCommit = _RAND_67[0:0];
  _RAND_68 = {1{`RANDOM}};
  bufData_2_isPriv = _RAND_68[0:0];
  _RAND_69 = {1{`RANDOM}};
  bufData_2_isIdle = _RAND_69[0:0];
  _RAND_70 = {1{`RANDOM}};
  bufData_2_waitStore = _RAND_70[0:0];
  _RAND_71 = {1{`RANDOM}};
  bufData_2_llbitSet = _RAND_71[0:0];
  _RAND_72 = {1{`RANDOM}};
  bufData_2_llbitClear = _RAND_72[0:0];
  _RAND_73 = {1{`RANDOM}};
  bufData_2_ibar = _RAND_73[0:0];
  _RAND_74 = {1{`RANDOM}};
  bufData_2_isCacop = _RAND_74[0:0];
  _RAND_75 = {1{`RANDOM}};
  bufData_2_cacopCacheType = _RAND_75[2:0];
  _RAND_76 = {1{`RANDOM}};
  bufData_2_cacopOperation = _RAND_76[1:0];
  _RAND_77 = {1{`RANDOM}};
  bufData_2_excp_excpVec = _RAND_77[16:0];
`endif // RANDOMIZE_REG_INIT
  `endif // RANDOMIZE
end // initial
`ifdef FIRRTL_AFTER_INITIAL
`FIRRTL_AFTER_INITIAL
`endif
`endif // SYNTHESIS
endmodule
