// ================================================================
// Auto-generated by CoreGen
// Generated at    : 2026-08-09 20:16:15
// Mode            : simu
// Git branch      : Dev_sys
// Git commit      : c54e60c
// Git message     : rm trash
// ================================================================

module DispatchLsqBuffer(
  input         clock,
  input         reset,
  input         io_enqReq_req_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_enqReq_req_bits_robIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_req_bits_robIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_req_bits_isLoad, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_req_bits_isStore, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_req_bits_sqIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_req_bits_sqIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_req_bits_lqIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_req_bits_lqIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_pc, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_inst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [3:0]  io_enqReq_toLsqData_ctrl_fuType, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_enqReq_toLsqData_ctrl_aluOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [3:0]  io_enqReq_toLsqData_ctrl_bruOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [3:0]  io_enqReq_toLsqData_ctrl_lsuOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [1:0]  io_enqReq_toLsqData_ctrl_barOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_ctrl_csrOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_ctrl_tlbOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_ctrl_mulOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_ctrl_divOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_ctrl_src1Type, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_ctrl_src2Type, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [3:0]  io_enqReq_toLsqData_ctrl_immType, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_rfWen, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_memRead, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_memWrite, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_csrWen, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_isBranch, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_isJump, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_isPriv, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_isIdle, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_waitForward, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_blockBackward, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_ctrl_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [16:0] io_enqReq_toLsqData_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_imm, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [13:0] io_enqReq_toLsqData_csrAddress, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_cacop_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_enqReq_toLsqData_cacop_code, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_cacop_cacheType, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [1:0]  io_enqReq_toLsqData_cacop_operation, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_pdInfo_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_pdInfo_isBr, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_pdInfo_isJal, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_pdInfo_isJalr, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_pdInfo_isCall, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_pdInfo_isRet, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_pdInfo_jumpTarget, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_bpuInfo_pc, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_bpuInfo_fallThrough, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_taken, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_bpuInfo_target, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [1:0]  io_enqReq_toLsqData_bpuInfo_takenOffset, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_meta_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_meta_btbHit, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_meta_btbIsJalr, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_meta_btbIsJal, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_meta_btbIsCall, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_meta_btbIsRet, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [1:0]  io_enqReq_toLsqData_bpuInfo_meta_btbOffset, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [1:0]  io_enqReq_toLsqData_bpuInfo_meta_phtCounter, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_bpuInfo_meta_rasTop, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_bpuInfo_meta_predTaken, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [31:0] io_enqReq_toLsqData_bpuInfo_meta_predTarget, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_enqReq_toLsqData_ldst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_enqReq_toLsqData_lrs1, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_enqReq_toLsqData_lrs2, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [6:0]  io_enqReq_toLsqData_pdst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [6:0]  io_enqReq_toLsqData_prs1, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [6:0]  io_enqReq_toLsqData_prs2, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [6:0]  io_enqReq_toLsqData_oldPdst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_snptId_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [2:0]  io_enqReq_toLsqData_snptId_bits, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_rs1Valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_rs2Valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_rdValid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_enqReq_toLsqData_robIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_enqReq_toLsqData_robIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_req_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [4:0]  io_deqReq_req_bits_robIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_req_bits_robIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_req_bits_isLoad, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_req_bits_isStore, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_req_bits_sqIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_req_bits_sqIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_req_bits_lqIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_req_bits_lqIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_pc, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_inst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [3:0]  io_deqReq_toLsqData_ctrl_fuType, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [4:0]  io_deqReq_toLsqData_ctrl_aluOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [3:0]  io_deqReq_toLsqData_ctrl_bruOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [3:0]  io_deqReq_toLsqData_ctrl_lsuOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [1:0]  io_deqReq_toLsqData_ctrl_barOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_ctrl_csrOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_ctrl_tlbOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_ctrl_mulOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_ctrl_divOp, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_ctrl_src1Type, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_ctrl_src2Type, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [3:0]  io_deqReq_toLsqData_ctrl_immType, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_rfWen, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_memRead, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_memWrite, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_csrWen, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_isBranch, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_isJump, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_isPriv, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_isIdle, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_waitForward, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_blockBackward, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_ctrl_flushOnCommit, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [16:0] io_deqReq_toLsqData_excp_excpVec, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_imm, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [13:0] io_deqReq_toLsqData_csrAddress, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_cacop_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [4:0]  io_deqReq_toLsqData_cacop_code, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_cacop_cacheType, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [1:0]  io_deqReq_toLsqData_cacop_operation, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_pdInfo_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_pdInfo_isBr, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_pdInfo_isJal, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_pdInfo_isJalr, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_pdInfo_isCall, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_pdInfo_isRet, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_pdInfo_jumpTarget, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_bpuInfo_pc, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_bpuInfo_fallThrough, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_taken, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_bpuInfo_target, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [1:0]  io_deqReq_toLsqData_bpuInfo_takenOffset, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_meta_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_meta_btbHit, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_meta_btbIsJalr, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_meta_btbIsJal, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_meta_btbIsCall, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_meta_btbIsRet, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [1:0]  io_deqReq_toLsqData_bpuInfo_meta_btbOffset, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [1:0]  io_deqReq_toLsqData_bpuInfo_meta_phtCounter, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_bpuInfo_meta_rasTop, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_bpuInfo_meta_predTaken, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [31:0] io_deqReq_toLsqData_bpuInfo_meta_predTarget, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [4:0]  io_deqReq_toLsqData_ldst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [4:0]  io_deqReq_toLsqData_lrs1, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [4:0]  io_deqReq_toLsqData_lrs2, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [6:0]  io_deqReq_toLsqData_pdst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [6:0]  io_deqReq_toLsqData_prs1, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [6:0]  io_deqReq_toLsqData_prs2, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [6:0]  io_deqReq_toLsqData_oldPdst, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_snptId_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [2:0]  io_deqReq_toLsqData_snptId_bits, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_rs1Valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_rs2Valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_rdValid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output [4:0]  io_deqReq_toLsqData_robIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_deqReq_toLsqData_robIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [3:0]  io_deqReq_lqHasEntries, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [3:0]  io_deqReq_sqHasEntries, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_redirectInfo_valid, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_redirectInfo_bits_doRedirect, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input  [4:0]  io_redirectInfo_bits_robIdx_value, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  input         io_redirectInfo_bits_robIdx_flag, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_dispatchLqFull, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_dispatchSqFull, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_bufHasPendingLoadNeedFlush, // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
  output        io_bufHasPendingStoreNeedFlush // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 21:14]
);
`ifdef RANDOMIZE_REG_INIT
  reg [31:0] _RAND_0;
  reg [31:0] _RAND_1;
  reg [31:0] _RAND_2;
  reg [31:0] _RAND_3;
  reg [31:0] _RAND_4;
  reg [31:0] _RAND_5;
  reg [31:0] _RAND_6;
  reg [31:0] _RAND_7;
  reg [31:0] _RAND_8;
  reg [31:0] _RAND_9;
  reg [31:0] _RAND_10;
  reg [31:0] _RAND_11;
  reg [31:0] _RAND_12;
  reg [31:0] _RAND_13;
  reg [31:0] _RAND_14;
  reg [31:0] _RAND_15;
  reg [31:0] _RAND_16;
  reg [31:0] _RAND_17;
  reg [31:0] _RAND_18;
  reg [31:0] _RAND_19;
  reg [31:0] _RAND_20;
  reg [31:0] _RAND_21;
  reg [31:0] _RAND_22;
  reg [31:0] _RAND_23;
  reg [31:0] _RAND_24;
  reg [31:0] _RAND_25;
  reg [31:0] _RAND_26;
  reg [31:0] _RAND_27;
  reg [31:0] _RAND_28;
  reg [31:0] _RAND_29;
  reg [31:0] _RAND_30;
  reg [31:0] _RAND_31;
  reg [31:0] _RAND_32;
  reg [31:0] _RAND_33;
  reg [31:0] _RAND_34;
  reg [31:0] _RAND_35;
  reg [31:0] _RAND_36;
  reg [31:0] _RAND_37;
  reg [31:0] _RAND_38;
  reg [31:0] _RAND_39;
  reg [31:0] _RAND_40;
  reg [31:0] _RAND_41;
  reg [31:0] _RAND_42;
  reg [31:0] _RAND_43;
  reg [31:0] _RAND_44;
  reg [31:0] _RAND_45;
  reg [31:0] _RAND_46;
  reg [31:0] _RAND_47;
  reg [31:0] _RAND_48;
  reg [31:0] _RAND_49;
  reg [31:0] _RAND_50;
  reg [31:0] _RAND_51;
  reg [31:0] _RAND_52;
  reg [31:0] _RAND_53;
  reg [31:0] _RAND_54;
  reg [31:0] _RAND_55;
  reg [31:0] _RAND_56;
  reg [31:0] _RAND_57;
  reg [31:0] _RAND_58;
  reg [31:0] _RAND_59;
  reg [31:0] _RAND_60;
  reg [31:0] _RAND_61;
  reg [31:0] _RAND_62;
  reg [31:0] _RAND_63;
  reg [31:0] _RAND_64;
  reg [31:0] _RAND_65;
  reg [31:0] _RAND_66;
  reg [31:0] _RAND_67;
  reg [31:0] _RAND_68;
  reg [31:0] _RAND_69;
  reg [31:0] _RAND_70;
  reg [31:0] _RAND_71;
  reg [31:0] _RAND_72;
  reg [31:0] _RAND_73;
  reg [31:0] _RAND_74;
  reg [31:0] _RAND_75;
  reg [31:0] _RAND_76;
  reg [31:0] _RAND_77;
  reg [31:0] _RAND_78;
`endif // RANDOMIZE_REG_INIT
  reg  bufValid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 52:29]
  reg  bufReq_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg [4:0] bufReq_bits_robIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg  bufReq_bits_robIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg  bufReq_bits_isLoad; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg  bufReq_bits_isStore; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg [2:0] bufReq_bits_sqIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg  bufReq_bits_sqIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg [2:0] bufReq_bits_lqIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg  bufReq_bits_lqIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
  reg [31:0] bufData_pc; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [31:0] bufData_inst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [3:0] bufData_ctrl_fuType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [4:0] bufData_ctrl_aluOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [3:0] bufData_ctrl_bruOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [3:0] bufData_ctrl_lsuOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [1:0] bufData_ctrl_barOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_ctrl_csrOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_ctrl_tlbOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_ctrl_mulOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_ctrl_divOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_ctrl_src1Type; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_ctrl_src2Type; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [3:0] bufData_ctrl_immType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_rfWen; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_memRead; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_memWrite; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_csrWen; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_isBranch; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_isJump; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_isPriv; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_isIdle; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_waitForward; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_blockBackward; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_ctrl_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [16:0] bufData_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [31:0] bufData_imm; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [13:0] bufData_csrAddress; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_cacop_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [4:0] bufData_cacop_code; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_cacop_cacheType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [1:0] bufData_cacop_operation; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_pdInfo_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_pdInfo_isBr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_pdInfo_isJal; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_pdInfo_isJalr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_pdInfo_isCall; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_pdInfo_isRet; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [31:0] bufData_pdInfo_jumpTarget; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [31:0] bufData_bpuInfo_pc; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [31:0] bufData_bpuInfo_fallThrough; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_taken; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [31:0] bufData_bpuInfo_target; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [1:0] bufData_bpuInfo_takenOffset; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_meta_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_meta_btbHit; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_meta_btbIsJalr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_meta_btbIsJal; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_meta_btbIsCall; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_meta_btbIsRet; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [1:0] bufData_bpuInfo_meta_btbOffset; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [1:0] bufData_bpuInfo_meta_phtCounter; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_bpuInfo_meta_rasTop; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_bpuInfo_meta_predTaken; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [31:0] bufData_bpuInfo_meta_predTarget; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [4:0] bufData_ldst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [4:0] bufData_lrs1; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [4:0] bufData_lrs2; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [6:0] bufData_pdst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [6:0] bufData_prs1; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [6:0] bufData_prs2; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [6:0] bufData_oldPdst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_snptId_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [2:0] bufData_snptId_bits; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_rs1Valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_rs2Valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_rdValid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg [4:0] bufData_robIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  reg  bufData_robIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
  wire  doRedirect = io_redirectInfo_valid & io_redirectInfo_bits_doRedirect; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 60:42]
  wire  _doFlush_T_2 = bufReq_bits_robIdx_value > io_redirectInfo_bits_robIdx_value; // @[src/main/scala/util/CircularQueuePtr.scala 146:18]
  wire  _doFlush_T_3 = bufReq_bits_robIdx_value < io_redirectInfo_bits_robIdx_value; // @[src/main/scala/util/CircularQueuePtr.scala 147:18]
  wire  _doFlush_T_4 = bufReq_bits_robIdx_flag == io_redirectInfo_bits_robIdx_flag ? _doFlush_T_2 : _doFlush_T_3; // @[src/main/scala/util/CircularQueuePtr.scala 145:8]
  wire  doFlush = doRedirect & bufValid & _doFlush_T_4; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 62:40]
  wire  _deqFire_T = ~doFlush; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 65:29]
  wire  deqFire = bufValid & ~doFlush; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 65:26]
  wire  canAccept = ~bufValid | deqFire; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 75:29]
  wire  enqFire = io_enqReq_req_valid & canAccept & _deqFire_T; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 76:50]
  wire  _GEN_0 = deqFire ? 1'h0 : bufValid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 86:23 88:14 52:29]
  wire  _GEN_1 = enqFire | _GEN_0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23 83:14]
  wire  bufPendingLoadCount = bufValid & bufReq_bits_isLoad; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 97:43]
  wire  bufPendingStoreCount = bufValid & bufReq_bits_isStore; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 98:43]
  wire [3:0] _GEN_159 = {{3'd0}, bufPendingLoadCount}; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 102:47]
  wire [4:0] _io_dispatchLqFull_T = io_deqReq_lqHasEntries + _GEN_159; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 102:47]
  wire [3:0] _GEN_160 = {{3'd0}, bufPendingStoreCount}; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 104:47]
  wire [4:0] _io_dispatchSqFull_T = io_deqReq_sqHasEntries + _GEN_160; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 104:47]
  assign io_deqReq_req_valid = bufValid & bufReq_valid & _deqFire_T; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 68:51]
  assign io_deqReq_req_bits_robIdx_value = bufReq_bits_robIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_req_bits_robIdx_flag = bufReq_bits_robIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_req_bits_isLoad = bufReq_bits_isLoad; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_req_bits_isStore = bufReq_bits_isStore; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_req_bits_sqIdx_value = bufReq_bits_sqIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_req_bits_sqIdx_flag = bufReq_bits_sqIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_req_bits_lqIdx_value = bufReq_bits_lqIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_req_bits_lqIdx_flag = bufReq_bits_lqIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 67:17]
  assign io_deqReq_toLsqData_pc = bufData_pc; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_inst = bufData_inst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_fuType = bufData_ctrl_fuType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_aluOp = bufData_ctrl_aluOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_bruOp = bufData_ctrl_bruOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_lsuOp = bufData_ctrl_lsuOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_barOp = bufData_ctrl_barOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_csrOp = bufData_ctrl_csrOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_tlbOp = bufData_ctrl_tlbOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_mulOp = bufData_ctrl_mulOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_divOp = bufData_ctrl_divOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_src1Type = bufData_ctrl_src1Type; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_src2Type = bufData_ctrl_src2Type; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_immType = bufData_ctrl_immType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_rfWen = bufData_ctrl_rfWen; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_memRead = bufData_ctrl_memRead; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_memWrite = bufData_ctrl_memWrite; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_csrWen = bufData_ctrl_csrWen; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_isBranch = bufData_ctrl_isBranch; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_isJump = bufData_ctrl_isJump; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_isPriv = bufData_ctrl_isPriv; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_isIdle = bufData_ctrl_isIdle; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_waitForward = bufData_ctrl_waitForward; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_blockBackward = bufData_ctrl_blockBackward; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ctrl_flushOnCommit = bufData_ctrl_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_excp_excpVec = bufData_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_imm = bufData_imm; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_csrAddress = bufData_csrAddress; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_cacop_valid = bufData_cacop_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_cacop_code = bufData_cacop_code; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_cacop_cacheType = bufData_cacop_cacheType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_cacop_operation = bufData_cacop_operation; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdInfo_valid = bufData_pdInfo_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdInfo_isBr = bufData_pdInfo_isBr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdInfo_isJal = bufData_pdInfo_isJal; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdInfo_isJalr = bufData_pdInfo_isJalr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdInfo_isCall = bufData_pdInfo_isCall; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdInfo_isRet = bufData_pdInfo_isRet; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdInfo_jumpTarget = bufData_pdInfo_jumpTarget; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_pc = bufData_bpuInfo_pc; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_fallThrough = bufData_bpuInfo_fallThrough; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_taken = bufData_bpuInfo_taken; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_target = bufData_bpuInfo_target; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_takenOffset = bufData_bpuInfo_takenOffset; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_valid = bufData_bpuInfo_meta_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_btbHit = bufData_bpuInfo_meta_btbHit; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_btbIsJalr = bufData_bpuInfo_meta_btbIsJalr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_btbIsJal = bufData_bpuInfo_meta_btbIsJal; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_btbIsCall = bufData_bpuInfo_meta_btbIsCall; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_btbIsRet = bufData_bpuInfo_meta_btbIsRet; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_btbOffset = bufData_bpuInfo_meta_btbOffset; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_phtCounter = bufData_bpuInfo_meta_phtCounter; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_rasTop = bufData_bpuInfo_meta_rasTop; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_predTaken = bufData_bpuInfo_meta_predTaken; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_bpuInfo_meta_predTarget = bufData_bpuInfo_meta_predTarget; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_ldst = bufData_ldst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_lrs1 = bufData_lrs1; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_lrs2 = bufData_lrs2; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_pdst = bufData_pdst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_prs1 = bufData_prs1; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_prs2 = bufData_prs2; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_oldPdst = bufData_oldPdst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_snptId_valid = bufData_snptId_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_snptId_bits = bufData_snptId_bits; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_rs1Valid = bufData_rs1Valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_rs2Valid = bufData_rs2Valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_rdValid = bufData_rdValid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_robIdx_value = bufData_robIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_deqReq_toLsqData_robIdx_flag = bufData_robIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 69:23]
  assign io_dispatchLqFull = _io_dispatchLqFull_T == 5'h8; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 102:70]
  assign io_dispatchSqFull = _io_dispatchSqFull_T == 5'h8; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 104:71]
  assign io_bufHasPendingLoadNeedFlush = bufPendingLoadCount & doFlush; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 106:68]
  assign io_bufHasPendingStoreNeedFlush = bufPendingStoreCount & doFlush; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 107:69]
  always @(posedge clock) begin
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 52:29]
      bufValid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 52:29]
    end else if (doFlush) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      bufValid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 80:14]
    end else begin
      bufValid <= _GEN_1;
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_valid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_valid <= io_enqReq_req_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_robIdx_value <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_robIdx_value <= io_enqReq_req_bits_robIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_robIdx_flag <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_robIdx_flag <= io_enqReq_req_bits_robIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_isLoad <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_isLoad <= io_enqReq_req_bits_isLoad; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_isStore <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_isStore <= io_enqReq_req_bits_isStore; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_sqIdx_value <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_sqIdx_value <= io_enqReq_req_bits_sqIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_sqIdx_flag <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_sqIdx_flag <= io_enqReq_req_bits_sqIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_lqIdx_value <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_lqIdx_value <= io_enqReq_req_bits_lqIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
      bufReq_bits_lqIdx_flag <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 57:28]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufReq_bits_lqIdx_flag <= io_enqReq_req_bits_lqIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 84:14]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pc <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pc <= io_enqReq_toLsqData_pc; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_inst <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_inst <= io_enqReq_toLsqData_inst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_fuType <= 4'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_fuType <= io_enqReq_toLsqData_ctrl_fuType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_aluOp <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_aluOp <= io_enqReq_toLsqData_ctrl_aluOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_bruOp <= 4'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_bruOp <= io_enqReq_toLsqData_ctrl_bruOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_lsuOp <= 4'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_lsuOp <= io_enqReq_toLsqData_ctrl_lsuOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_barOp <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_barOp <= io_enqReq_toLsqData_ctrl_barOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_csrOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_csrOp <= io_enqReq_toLsqData_ctrl_csrOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_tlbOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_tlbOp <= io_enqReq_toLsqData_ctrl_tlbOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_mulOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_mulOp <= io_enqReq_toLsqData_ctrl_mulOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_divOp <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_divOp <= io_enqReq_toLsqData_ctrl_divOp; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_src1Type <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_src1Type <= io_enqReq_toLsqData_ctrl_src1Type; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_src2Type <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_src2Type <= io_enqReq_toLsqData_ctrl_src2Type; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_immType <= 4'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_immType <= io_enqReq_toLsqData_ctrl_immType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_rfWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_rfWen <= io_enqReq_toLsqData_ctrl_rfWen; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_memRead <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_memRead <= io_enqReq_toLsqData_ctrl_memRead; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_memWrite <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_memWrite <= io_enqReq_toLsqData_ctrl_memWrite; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_csrWen <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_csrWen <= io_enqReq_toLsqData_ctrl_csrWen; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_isBranch <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_isBranch <= io_enqReq_toLsqData_ctrl_isBranch; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_isJump <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_isJump <= io_enqReq_toLsqData_ctrl_isJump; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_isPriv <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_isPriv <= io_enqReq_toLsqData_ctrl_isPriv; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_isIdle <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_isIdle <= io_enqReq_toLsqData_ctrl_isIdle; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_waitForward <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_waitForward <= io_enqReq_toLsqData_ctrl_waitForward; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_blockBackward <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_blockBackward <= io_enqReq_toLsqData_ctrl_blockBackward; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ctrl_flushOnCommit <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ctrl_flushOnCommit <= io_enqReq_toLsqData_ctrl_flushOnCommit; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_excp_excpVec <= 17'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_excp_excpVec <= io_enqReq_toLsqData_excp_excpVec; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_imm <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_imm <= io_enqReq_toLsqData_imm; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_csrAddress <= 14'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_csrAddress <= io_enqReq_toLsqData_csrAddress; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_cacop_valid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_cacop_valid <= io_enqReq_toLsqData_cacop_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_cacop_code <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_cacop_code <= io_enqReq_toLsqData_cacop_code; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_cacop_cacheType <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_cacop_cacheType <= io_enqReq_toLsqData_cacop_cacheType; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_cacop_operation <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_cacop_operation <= io_enqReq_toLsqData_cacop_operation; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdInfo_valid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdInfo_valid <= io_enqReq_toLsqData_pdInfo_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdInfo_isBr <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdInfo_isBr <= io_enqReq_toLsqData_pdInfo_isBr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdInfo_isJal <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdInfo_isJal <= io_enqReq_toLsqData_pdInfo_isJal; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdInfo_isJalr <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdInfo_isJalr <= io_enqReq_toLsqData_pdInfo_isJalr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdInfo_isCall <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdInfo_isCall <= io_enqReq_toLsqData_pdInfo_isCall; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdInfo_isRet <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdInfo_isRet <= io_enqReq_toLsqData_pdInfo_isRet; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdInfo_jumpTarget <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdInfo_jumpTarget <= io_enqReq_toLsqData_pdInfo_jumpTarget; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_pc <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_pc <= io_enqReq_toLsqData_bpuInfo_pc; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_fallThrough <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_fallThrough <= io_enqReq_toLsqData_bpuInfo_fallThrough; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_taken <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_taken <= io_enqReq_toLsqData_bpuInfo_taken; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_target <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_target <= io_enqReq_toLsqData_bpuInfo_target; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_takenOffset <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_takenOffset <= io_enqReq_toLsqData_bpuInfo_takenOffset; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_valid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_valid <= io_enqReq_toLsqData_bpuInfo_meta_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_btbHit <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_btbHit <= io_enqReq_toLsqData_bpuInfo_meta_btbHit; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_btbIsJalr <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_btbIsJalr <= io_enqReq_toLsqData_bpuInfo_meta_btbIsJalr; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_btbIsJal <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_btbIsJal <= io_enqReq_toLsqData_bpuInfo_meta_btbIsJal; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_btbIsCall <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_btbIsCall <= io_enqReq_toLsqData_bpuInfo_meta_btbIsCall; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_btbIsRet <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_btbIsRet <= io_enqReq_toLsqData_bpuInfo_meta_btbIsRet; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_btbOffset <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_btbOffset <= io_enqReq_toLsqData_bpuInfo_meta_btbOffset; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_phtCounter <= 2'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_phtCounter <= io_enqReq_toLsqData_bpuInfo_meta_phtCounter; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_rasTop <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_rasTop <= io_enqReq_toLsqData_bpuInfo_meta_rasTop; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_predTaken <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_predTaken <= io_enqReq_toLsqData_bpuInfo_meta_predTaken; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_bpuInfo_meta_predTarget <= 32'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_bpuInfo_meta_predTarget <= io_enqReq_toLsqData_bpuInfo_meta_predTarget; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_ldst <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_ldst <= io_enqReq_toLsqData_ldst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_lrs1 <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_lrs1 <= io_enqReq_toLsqData_lrs1; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_lrs2 <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_lrs2 <= io_enqReq_toLsqData_lrs2; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_pdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_pdst <= io_enqReq_toLsqData_pdst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_prs1 <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_prs1 <= io_enqReq_toLsqData_prs1; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_prs2 <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_prs2 <= io_enqReq_toLsqData_prs2; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_oldPdst <= 7'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_oldPdst <= io_enqReq_toLsqData_oldPdst; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_snptId_valid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_snptId_valid <= io_enqReq_toLsqData_snptId_valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_snptId_bits <= 3'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_snptId_bits <= io_enqReq_toLsqData_snptId_bits; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_rs1Valid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_rs1Valid <= io_enqReq_toLsqData_rs1Valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_rs2Valid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_rs2Valid <= io_enqReq_toLsqData_rs2Valid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_rdValid <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_rdValid <= io_enqReq_toLsqData_rdValid; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_robIdx_value <= 5'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_robIdx_value <= io_enqReq_toLsqData_robIdx_value; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
    if (reset) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
      bufData_robIdx_flag <= 1'h0; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 58:29]
    end else if (!(doFlush)) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 78:17]
      if (enqFire) begin // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 81:23]
        bufData_robIdx_flag <= io_enqReq_toLsqData_robIdx_flag; // @[src/main/scala/backend/dispatch/DispatchLsqBuffer.scala 85:15]
      end
    end
  end
// Register and memory initialization
`ifdef RANDOMIZE_GARBAGE_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_INVALID_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_REG_INIT
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_MEM_INIT
`define RANDOMIZE
`endif
`ifndef RANDOM
`define RANDOM $random
`endif
`ifdef RANDOMIZE_MEM_INIT
  integer initvar;
`endif
`ifndef SYNTHESIS
`ifdef FIRRTL_BEFORE_INITIAL
`FIRRTL_BEFORE_INITIAL
`endif
initial begin
  `ifdef RANDOMIZE
    `ifdef INIT_RANDOM
      `INIT_RANDOM
    `endif
    `ifndef VERILATOR
      `ifdef RANDOMIZE_DELAY
        #`RANDOMIZE_DELAY begin end
      `else
        #0.002 begin end
      `endif
    `endif
`ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {1{`RANDOM}};
  bufValid = _RAND_0[0:0];
  _RAND_1 = {1{`RANDOM}};
  bufReq_valid = _RAND_1[0:0];
  _RAND_2 = {1{`RANDOM}};
  bufReq_bits_robIdx_value = _RAND_2[4:0];
  _RAND_3 = {1{`RANDOM}};
  bufReq_bits_robIdx_flag = _RAND_3[0:0];
  _RAND_4 = {1{`RANDOM}};
  bufReq_bits_isLoad = _RAND_4[0:0];
  _RAND_5 = {1{`RANDOM}};
  bufReq_bits_isStore = _RAND_5[0:0];
  _RAND_6 = {1{`RANDOM}};
  bufReq_bits_sqIdx_value = _RAND_6[2:0];
  _RAND_7 = {1{`RANDOM}};
  bufReq_bits_sqIdx_flag = _RAND_7[0:0];
  _RAND_8 = {1{`RANDOM}};
  bufReq_bits_lqIdx_value = _RAND_8[2:0];
  _RAND_9 = {1{`RANDOM}};
  bufReq_bits_lqIdx_flag = _RAND_9[0:0];
  _RAND_10 = {1{`RANDOM}};
  bufData_pc = _RAND_10[31:0];
  _RAND_11 = {1{`RANDOM}};
  bufData_inst = _RAND_11[31:0];
  _RAND_12 = {1{`RANDOM}};
  bufData_ctrl_fuType = _RAND_12[3:0];
  _RAND_13 = {1{`RANDOM}};
  bufData_ctrl_aluOp = _RAND_13[4:0];
  _RAND_14 = {1{`RANDOM}};
  bufData_ctrl_bruOp = _RAND_14[3:0];
  _RAND_15 = {1{`RANDOM}};
  bufData_ctrl_lsuOp = _RAND_15[3:0];
  _RAND_16 = {1{`RANDOM}};
  bufData_ctrl_barOp = _RAND_16[1:0];
  _RAND_17 = {1{`RANDOM}};
  bufData_ctrl_csrOp = _RAND_17[2:0];
  _RAND_18 = {1{`RANDOM}};
  bufData_ctrl_tlbOp = _RAND_18[2:0];
  _RAND_19 = {1{`RANDOM}};
  bufData_ctrl_mulOp = _RAND_19[2:0];
  _RAND_20 = {1{`RANDOM}};
  bufData_ctrl_divOp = _RAND_20[2:0];
  _RAND_21 = {1{`RANDOM}};
  bufData_ctrl_src1Type = _RAND_21[2:0];
  _RAND_22 = {1{`RANDOM}};
  bufData_ctrl_src2Type = _RAND_22[2:0];
  _RAND_23 = {1{`RANDOM}};
  bufData_ctrl_immType = _RAND_23[3:0];
  _RAND_24 = {1{`RANDOM}};
  bufData_ctrl_rfWen = _RAND_24[0:0];
  _RAND_25 = {1{`RANDOM}};
  bufData_ctrl_memRead = _RAND_25[0:0];
  _RAND_26 = {1{`RANDOM}};
  bufData_ctrl_memWrite = _RAND_26[0:0];
  _RAND_27 = {1{`RANDOM}};
  bufData_ctrl_csrWen = _RAND_27[0:0];
  _RAND_28 = {1{`RANDOM}};
  bufData_ctrl_isBranch = _RAND_28[0:0];
  _RAND_29 = {1{`RANDOM}};
  bufData_ctrl_isJump = _RAND_29[0:0];
  _RAND_30 = {1{`RANDOM}};
  bufData_ctrl_isPriv = _RAND_30[0:0];
  _RAND_31 = {1{`RANDOM}};
  bufData_ctrl_isIdle = _RAND_31[0:0];
  _RAND_32 = {1{`RANDOM}};
  bufData_ctrl_waitForward = _RAND_32[0:0];
  _RAND_33 = {1{`RANDOM}};
  bufData_ctrl_blockBackward = _RAND_33[0:0];
  _RAND_34 = {1{`RANDOM}};
  bufData_ctrl_flushOnCommit = _RAND_34[0:0];
  _RAND_35 = {1{`RANDOM}};
  bufData_excp_excpVec = _RAND_35[16:0];
  _RAND_36 = {1{`RANDOM}};
  bufData_imm = _RAND_36[31:0];
  _RAND_37 = {1{`RANDOM}};
  bufData_csrAddress = _RAND_37[13:0];
  _RAND_38 = {1{`RANDOM}};
  bufData_cacop_valid = _RAND_38[0:0];
  _RAND_39 = {1{`RANDOM}};
  bufData_cacop_code = _RAND_39[4:0];
  _RAND_40 = {1{`RANDOM}};
  bufData_cacop_cacheType = _RAND_40[2:0];
  _RAND_41 = {1{`RANDOM}};
  bufData_cacop_operation = _RAND_41[1:0];
  _RAND_42 = {1{`RANDOM}};
  bufData_pdInfo_valid = _RAND_42[0:0];
  _RAND_43 = {1{`RANDOM}};
  bufData_pdInfo_isBr = _RAND_43[0:0];
  _RAND_44 = {1{`RANDOM}};
  bufData_pdInfo_isJal = _RAND_44[0:0];
  _RAND_45 = {1{`RANDOM}};
  bufData_pdInfo_isJalr = _RAND_45[0:0];
  _RAND_46 = {1{`RANDOM}};
  bufData_pdInfo_isCall = _RAND_46[0:0];
  _RAND_47 = {1{`RANDOM}};
  bufData_pdInfo_isRet = _RAND_47[0:0];
  _RAND_48 = {1{`RANDOM}};
  bufData_pdInfo_jumpTarget = _RAND_48[31:0];
  _RAND_49 = {1{`RANDOM}};
  bufData_bpuInfo_pc = _RAND_49[31:0];
  _RAND_50 = {1{`RANDOM}};
  bufData_bpuInfo_fallThrough = _RAND_50[31:0];
  _RAND_51 = {1{`RANDOM}};
  bufData_bpuInfo_taken = _RAND_51[0:0];
  _RAND_52 = {1{`RANDOM}};
  bufData_bpuInfo_target = _RAND_52[31:0];
  _RAND_53 = {1{`RANDOM}};
  bufData_bpuInfo_takenOffset = _RAND_53[1:0];
  _RAND_54 = {1{`RANDOM}};
  bufData_bpuInfo_meta_valid = _RAND_54[0:0];
  _RAND_55 = {1{`RANDOM}};
  bufData_bpuInfo_meta_btbHit = _RAND_55[0:0];
  _RAND_56 = {1{`RANDOM}};
  bufData_bpuInfo_meta_btbIsJalr = _RAND_56[0:0];
  _RAND_57 = {1{`RANDOM}};
  bufData_bpuInfo_meta_btbIsJal = _RAND_57[0:0];
  _RAND_58 = {1{`RANDOM}};
  bufData_bpuInfo_meta_btbIsCall = _RAND_58[0:0];
  _RAND_59 = {1{`RANDOM}};
  bufData_bpuInfo_meta_btbIsRet = _RAND_59[0:0];
  _RAND_60 = {1{`RANDOM}};
  bufData_bpuInfo_meta_btbOffset = _RAND_60[1:0];
  _RAND_61 = {1{`RANDOM}};
  bufData_bpuInfo_meta_phtCounter = _RAND_61[1:0];
  _RAND_62 = {1{`RANDOM}};
  bufData_bpuInfo_meta_rasTop = _RAND_62[2:0];
  _RAND_63 = {1{`RANDOM}};
  bufData_bpuInfo_meta_predTaken = _RAND_63[0:0];
  _RAND_64 = {1{`RANDOM}};
  bufData_bpuInfo_meta_predTarget = _RAND_64[31:0];
  _RAND_65 = {1{`RANDOM}};
  bufData_ldst = _RAND_65[4:0];
  _RAND_66 = {1{`RANDOM}};
  bufData_lrs1 = _RAND_66[4:0];
  _RAND_67 = {1{`RANDOM}};
  bufData_lrs2 = _RAND_67[4:0];
  _RAND_68 = {1{`RANDOM}};
  bufData_pdst = _RAND_68[6:0];
  _RAND_69 = {1{`RANDOM}};
  bufData_prs1 = _RAND_69[6:0];
  _RAND_70 = {1{`RANDOM}};
  bufData_prs2 = _RAND_70[6:0];
  _RAND_71 = {1{`RANDOM}};
  bufData_oldPdst = _RAND_71[6:0];
  _RAND_72 = {1{`RANDOM}};
  bufData_snptId_valid = _RAND_72[0:0];
  _RAND_73 = {1{`RANDOM}};
  bufData_snptId_bits = _RAND_73[2:0];
  _RAND_74 = {1{`RANDOM}};
  bufData_rs1Valid = _RAND_74[0:0];
  _RAND_75 = {1{`RANDOM}};
  bufData_rs2Valid = _RAND_75[0:0];
  _RAND_76 = {1{`RANDOM}};
  bufData_rdValid = _RAND_76[0:0];
  _RAND_77 = {1{`RANDOM}};
  bufData_robIdx_value = _RAND_77[4:0];
  _RAND_78 = {1{`RANDOM}};
  bufData_robIdx_flag = _RAND_78[0:0];
`endif // RANDOMIZE_REG_INIT
  `endif // RANDOMIZE
end // initial
`ifdef FIRRTL_AFTER_INITIAL
`FIRRTL_AFTER_INITIAL
`endif
`endif // SYNTHESIS
endmodule
