// ================================================================
// Auto-generated by CoreGen
// Generated at    : 2026-08-09 20:16:15
// Mode            : simu
// Git branch      : Dev_sys
// Git commit      : c54e60c
// Git message     : rm trash
// ================================================================

module ICacheArray(
  input          clock,
  input          reset,
  input          io_read_req_valid, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  input  [5:0]   io_read_req_idx, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output         io_read_resp_valid, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output         io_read_resp_data_cacheLine_0_has, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [19:0]  io_read_resp_data_cacheLine_0_tag, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [511:0] io_read_resp_data_cacheLine_0_data, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output         io_read_resp_data_cacheLine_1_has, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [19:0]  io_read_resp_data_cacheLine_1_tag, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [511:0] io_read_resp_data_cacheLine_1_data, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output         io_read_resp_data_cacheLine_2_has, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [19:0]  io_read_resp_data_cacheLine_2_tag, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [511:0] io_read_resp_data_cacheLine_2_data, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output         io_read_resp_data_cacheLine_3_has, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [19:0]  io_read_resp_data_cacheLine_3_tag, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  output [511:0] io_read_resp_data_cacheLine_3_data, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  input          io_write_valid, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  input  [5:0]   io_write_idx, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  input  [1:0]   io_write_way, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  input  [19:0]  io_write_tag, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  input  [511:0] io_write_data, // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
  input          io_invalidate // @[src/main/scala/frontend/icache/ICacheArray.scala 31:14]
);
`ifdef RANDOMIZE_REG_INIT
  reg [63:0] _RAND_0;
  reg [63:0] _RAND_1;
  reg [63:0] _RAND_2;
  reg [63:0] _RAND_3;
  reg [31:0] _RAND_4;
  reg [31:0] _RAND_5;
`endif // RANDOMIZE_REG_INIT
  wire  SimpleBlockRAM_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_1_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_1_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_1_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_1_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_1_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_1_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_1_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_1_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_2_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_2_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_2_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_2_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_2_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_2_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_2_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_2_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_3_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_3_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_3_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_3_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_3_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_3_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [5:0] SimpleBlockRAM_3_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire [19:0] SimpleBlockRAM_3_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
  wire  SimpleBlockRAM_4_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_4_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_4_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_4_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_4_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_4_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_4_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_4_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_5_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_5_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_5_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_5_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_5_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_5_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_5_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_5_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_6_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_6_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_6_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_6_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_6_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_6_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_6_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_6_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_7_clock; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_7_reset; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_7_io_wr_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_7_io_wr_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_7_io_wr_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire  SimpleBlockRAM_7_io_rd_en; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [5:0] SimpleBlockRAM_7_io_rd_addr; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  wire [511:0] SimpleBlockRAM_7_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
  reg [63:0] validArray_0; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
  reg [63:0] validArray_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
  reg [63:0] validArray_2; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
  reg [63:0] validArray_3; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
  reg [5:0] readIdxReg; // @[src/main/scala/frontend/icache/ICacheArray.scala 82:29]
  wire [63:0] _readRespData_cacheLine_0_has_T = validArray_0 >> readIdxReg; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  wire [63:0] _readRespData_cacheLine_1_has_T = validArray_1 >> readIdxReg; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  wire [63:0] _readRespData_cacheLine_2_has_T = validArray_2 >> readIdxReg; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  wire [63:0] _readRespData_cacheLine_3_has_T = validArray_3 >> readIdxReg; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  reg  anyRdValid; // @[src/main/scala/frontend/icache/ICacheArray.scala 98:28]
  wire [3:0] writeWayOneHot = 4'h1 << io_write_way; // @[src/main/scala/chisel3/util/OneHot.scala 58:35]
  wire  waySel = writeWayOneHot[0]; // @[src/main/scala/frontend/icache/ICacheArray.scala 109:32]
  wire  metaBRAMs_0_wr_en = io_write_valid & waySel; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  wire [63:0] _validArray_0_T = 64'h1 << io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:48]
  wire [63:0] _validArray_0_T_1 = validArray_0 | _validArray_0_T; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:48]
  wire  waySel_1 = writeWayOneHot[1]; // @[src/main/scala/frontend/icache/ICacheArray.scala 109:32]
  wire  metaBRAMs_1_wr_en = io_write_valid & waySel_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  wire [63:0] _validArray_1_T_1 = validArray_1 | _validArray_0_T; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:48]
  wire  waySel_2 = writeWayOneHot[2]; // @[src/main/scala/frontend/icache/ICacheArray.scala 109:32]
  wire  metaBRAMs_2_wr_en = io_write_valid & waySel_2; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  wire [63:0] _validArray_2_T_1 = validArray_2 | _validArray_0_T; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:48]
  wire  waySel_3 = writeWayOneHot[3]; // @[src/main/scala/frontend/icache/ICacheArray.scala 109:32]
  wire  metaBRAMs_3_wr_en = io_write_valid & waySel_3; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  wire [63:0] _validArray_3_T_1 = validArray_3 | _validArray_0_T; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:48]
  SimpleBlockRAM_4 SimpleBlockRAM ( // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
    .clock(SimpleBlockRAM_clock),
    .reset(SimpleBlockRAM_reset),
    .io_wr_en(SimpleBlockRAM_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_io_wr_data),
    .io_rd_en(SimpleBlockRAM_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_io_rd_data)
  );
  SimpleBlockRAM_4 SimpleBlockRAM_1 ( // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
    .clock(SimpleBlockRAM_1_clock),
    .reset(SimpleBlockRAM_1_reset),
    .io_wr_en(SimpleBlockRAM_1_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_1_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_1_io_wr_data),
    .io_rd_en(SimpleBlockRAM_1_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_1_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_1_io_rd_data)
  );
  SimpleBlockRAM_4 SimpleBlockRAM_2 ( // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
    .clock(SimpleBlockRAM_2_clock),
    .reset(SimpleBlockRAM_2_reset),
    .io_wr_en(SimpleBlockRAM_2_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_2_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_2_io_wr_data),
    .io_rd_en(SimpleBlockRAM_2_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_2_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_2_io_rd_data)
  );
  SimpleBlockRAM_4 SimpleBlockRAM_3 ( // @[src/main/scala/frontend/icache/ICacheArray.scala 51:11]
    .clock(SimpleBlockRAM_3_clock),
    .reset(SimpleBlockRAM_3_reset),
    .io_wr_en(SimpleBlockRAM_3_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_3_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_3_io_wr_data),
    .io_rd_en(SimpleBlockRAM_3_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_3_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_3_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_4 ( // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
    .clock(SimpleBlockRAM_4_clock),
    .reset(SimpleBlockRAM_4_reset),
    .io_wr_en(SimpleBlockRAM_4_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_4_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_4_io_wr_data),
    .io_rd_en(SimpleBlockRAM_4_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_4_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_4_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_5 ( // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
    .clock(SimpleBlockRAM_5_clock),
    .reset(SimpleBlockRAM_5_reset),
    .io_wr_en(SimpleBlockRAM_5_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_5_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_5_io_wr_data),
    .io_rd_en(SimpleBlockRAM_5_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_5_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_5_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_6 ( // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
    .clock(SimpleBlockRAM_6_clock),
    .reset(SimpleBlockRAM_6_reset),
    .io_wr_en(SimpleBlockRAM_6_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_6_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_6_io_wr_data),
    .io_rd_en(SimpleBlockRAM_6_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_6_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_6_io_rd_data)
  );
  SimpleBlockRAM_8 SimpleBlockRAM_7 ( // @[src/main/scala/frontend/icache/ICacheArray.scala 60:11]
    .clock(SimpleBlockRAM_7_clock),
    .reset(SimpleBlockRAM_7_reset),
    .io_wr_en(SimpleBlockRAM_7_io_wr_en),
    .io_wr_addr(SimpleBlockRAM_7_io_wr_addr),
    .io_wr_data(SimpleBlockRAM_7_io_wr_data),
    .io_rd_en(SimpleBlockRAM_7_io_rd_en),
    .io_rd_addr(SimpleBlockRAM_7_io_rd_addr),
    .io_rd_data(SimpleBlockRAM_7_io_rd_data)
  );
  assign io_read_resp_valid = anyRdValid; // @[src/main/scala/frontend/icache/ICacheArray.scala 100:22]
  assign io_read_resp_data_cacheLine_0_has = _readRespData_cacheLine_0_has_T[0]; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  assign io_read_resp_data_cacheLine_0_tag = SimpleBlockRAM_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:{26,26}]
  assign io_read_resp_data_cacheLine_0_data = SimpleBlockRAM_4_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:{26,26}]
  assign io_read_resp_data_cacheLine_1_has = _readRespData_cacheLine_1_has_T[0]; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  assign io_read_resp_data_cacheLine_1_tag = SimpleBlockRAM_1_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:{26,26}]
  assign io_read_resp_data_cacheLine_1_data = SimpleBlockRAM_5_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:{26,26}]
  assign io_read_resp_data_cacheLine_2_has = _readRespData_cacheLine_2_has_T[0]; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  assign io_read_resp_data_cacheLine_2_tag = SimpleBlockRAM_2_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:{26,26}]
  assign io_read_resp_data_cacheLine_2_data = SimpleBlockRAM_6_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:{26,26}]
  assign io_read_resp_data_cacheLine_3_has = _readRespData_cacheLine_3_has_T[0]; // @[src/main/scala/frontend/icache/ICacheArray.scala 90:56]
  assign io_read_resp_data_cacheLine_3_tag = SimpleBlockRAM_3_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:{26,26}]
  assign io_read_resp_data_cacheLine_3_data = SimpleBlockRAM_7_io_rd_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:{26,26}]
  assign SimpleBlockRAM_clock = clock;
  assign SimpleBlockRAM_reset = reset;
  assign SimpleBlockRAM_io_wr_en = io_write_valid & waySel; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  assign SimpleBlockRAM_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_io_wr_data = io_write_tag; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 117:28 145:30]
  assign SimpleBlockRAM_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 70:28]
  assign SimpleBlockRAM_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 71:28]
  assign SimpleBlockRAM_1_clock = clock;
  assign SimpleBlockRAM_1_reset = reset;
  assign SimpleBlockRAM_1_io_wr_en = io_write_valid & waySel_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  assign SimpleBlockRAM_1_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_1_io_wr_data = io_write_tag; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 117:28 145:30]
  assign SimpleBlockRAM_1_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 70:28]
  assign SimpleBlockRAM_1_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 71:28]
  assign SimpleBlockRAM_2_clock = clock;
  assign SimpleBlockRAM_2_reset = reset;
  assign SimpleBlockRAM_2_io_wr_en = io_write_valid & waySel_2; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  assign SimpleBlockRAM_2_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_2_io_wr_data = io_write_tag; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 117:28 145:30]
  assign SimpleBlockRAM_2_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 70:28]
  assign SimpleBlockRAM_2_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 71:28]
  assign SimpleBlockRAM_3_clock = clock;
  assign SimpleBlockRAM_3_reset = reset;
  assign SimpleBlockRAM_3_io_wr_en = io_write_valid & waySel_3; // @[src/main/scala/frontend/icache/ICacheArray.scala 115:46]
  assign SimpleBlockRAM_3_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_3_io_wr_data = io_write_tag; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 117:28 145:30]
  assign SimpleBlockRAM_3_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 70:28]
  assign SimpleBlockRAM_3_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 50:26 71:28]
  assign SimpleBlockRAM_4_clock = clock;
  assign SimpleBlockRAM_4_reset = reset;
  assign SimpleBlockRAM_4_io_wr_en = io_write_valid & waySel; // @[src/main/scala/frontend/icache/ICacheArray.scala 124:46]
  assign SimpleBlockRAM_4_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_4_io_wr_data = io_write_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 126:28 150:30]
  assign SimpleBlockRAM_4_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 72:28]
  assign SimpleBlockRAM_4_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 73:28]
  assign SimpleBlockRAM_5_clock = clock;
  assign SimpleBlockRAM_5_reset = reset;
  assign SimpleBlockRAM_5_io_wr_en = io_write_valid & waySel_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 124:46]
  assign SimpleBlockRAM_5_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_5_io_wr_data = io_write_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 126:28 150:30]
  assign SimpleBlockRAM_5_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 72:28]
  assign SimpleBlockRAM_5_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 73:28]
  assign SimpleBlockRAM_6_clock = clock;
  assign SimpleBlockRAM_6_reset = reset;
  assign SimpleBlockRAM_6_io_wr_en = io_write_valid & waySel_2; // @[src/main/scala/frontend/icache/ICacheArray.scala 124:46]
  assign SimpleBlockRAM_6_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_6_io_wr_data = io_write_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 126:28 150:30]
  assign SimpleBlockRAM_6_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 72:28]
  assign SimpleBlockRAM_6_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 73:28]
  assign SimpleBlockRAM_7_clock = clock;
  assign SimpleBlockRAM_7_reset = reset;
  assign SimpleBlockRAM_7_io_wr_en = io_write_valid & waySel_3; // @[src/main/scala/frontend/icache/ICacheArray.scala 124:46]
  assign SimpleBlockRAM_7_io_wr_addr = io_write_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 116:28 144:30]
  assign SimpleBlockRAM_7_io_wr_data = io_write_data; // @[src/main/scala/frontend/icache/ICacheArray.scala 140:25 126:28 150:30]
  assign SimpleBlockRAM_7_io_rd_en = io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 72:28]
  assign SimpleBlockRAM_7_io_rd_addr = io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 59:26 73:28]
  always @(posedge clock) begin
    if (reset) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
      validArray_0 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
    end else if (io_invalidate) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 156:23]
      validArray_0 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 158:23]
    end else if (metaBRAMs_0_wr_en) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 119:36]
      validArray_0 <= _validArray_0_T_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:23]
    end
    if (reset) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
      validArray_1 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
    end else if (io_invalidate) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 156:23]
      validArray_1 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 158:23]
    end else if (metaBRAMs_1_wr_en) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 119:36]
      validArray_1 <= _validArray_1_T_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:23]
    end
    if (reset) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
      validArray_2 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
    end else if (io_invalidate) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 156:23]
      validArray_2 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 158:23]
    end else if (metaBRAMs_2_wr_en) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 119:36]
      validArray_2 <= _validArray_2_T_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:23]
    end
    if (reset) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
      validArray_3 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 48:27]
    end else if (io_invalidate) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 156:23]
      validArray_3 <= 64'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 158:23]
    end else if (metaBRAMs_3_wr_en) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 119:36]
      validArray_3 <= _validArray_3_T_1; // @[src/main/scala/frontend/icache/ICacheArray.scala 120:23]
    end
    if (reset) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 82:29]
      readIdxReg <= 6'h0; // @[src/main/scala/frontend/icache/ICacheArray.scala 82:29]
    end else if (io_read_req_valid) begin // @[src/main/scala/frontend/icache/ICacheArray.scala 82:29]
      readIdxReg <= io_read_req_idx; // @[src/main/scala/frontend/icache/ICacheArray.scala 82:29]
    end
    anyRdValid <= io_read_req_valid; // @[src/main/scala/frontend/icache/ICacheArray.scala 98:28]
  end
// Register and memory initialization
`ifdef RANDOMIZE_GARBAGE_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_INVALID_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_REG_INIT
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_MEM_INIT
`define RANDOMIZE
`endif
`ifndef RANDOM
`define RANDOM $random
`endif
`ifdef RANDOMIZE_MEM_INIT
  integer initvar;
`endif
`ifndef SYNTHESIS
`ifdef FIRRTL_BEFORE_INITIAL
`FIRRTL_BEFORE_INITIAL
`endif
initial begin
  `ifdef RANDOMIZE
    `ifdef INIT_RANDOM
      `INIT_RANDOM
    `endif
    `ifndef VERILATOR
      `ifdef RANDOMIZE_DELAY
        #`RANDOMIZE_DELAY begin end
      `else
        #0.002 begin end
      `endif
    `endif
`ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {2{`RANDOM}};
  validArray_0 = _RAND_0[63:0];
  _RAND_1 = {2{`RANDOM}};
  validArray_1 = _RAND_1[63:0];
  _RAND_2 = {2{`RANDOM}};
  validArray_2 = _RAND_2[63:0];
  _RAND_3 = {2{`RANDOM}};
  validArray_3 = _RAND_3[63:0];
  _RAND_4 = {1{`RANDOM}};
  readIdxReg = _RAND_4[5:0];
  _RAND_5 = {1{`RANDOM}};
  anyRdValid = _RAND_5[0:0];
`endif // RANDOMIZE_REG_INIT
  `endif // RANDOMIZE
end // initial
`ifdef FIRRTL_AFTER_INITIAL
`FIRRTL_AFTER_INITIAL
`endif
`endif // SYNTHESIS
endmodule
