module Arbiter(
  output        io_in_0_ready, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input         io_in_0_valid, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [3:0]  io_in_0_bits_arid, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [31:0] io_in_0_bits_araddr, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [7:0]  io_in_0_bits_arlen, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [2:0]  io_in_0_bits_arsize, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  output        io_in_1_ready, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input         io_in_1_valid, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [3:0]  io_in_1_bits_arid, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [31:0] io_in_1_bits_araddr, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [7:0]  io_in_1_bits_arlen, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input  [2:0]  io_in_1_bits_arsize, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  input         io_out_ready, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  output        io_out_valid, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  output [3:0]  io_out_bits_arid, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  output [31:0] io_out_bits_araddr, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  output [7:0]  io_out_bits_arlen, // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
  output [2:0]  io_out_bits_arsize // @[src/main/scala/chisel3/util/Arbiter.scala 134:14]
);
  wire  grant_1 = ~io_in_0_valid; // @[src/main/scala/chisel3/util/Arbiter.scala 45:78]
  assign io_in_0_ready = io_out_ready; // @[src/main/scala/chisel3/util/Arbiter.scala 147:19]
  assign io_in_1_ready = grant_1 & io_out_ready; // @[src/main/scala/chisel3/util/Arbiter.scala 147:19]
  assign io_out_valid = ~grant_1 | io_in_1_valid; // @[src/main/scala/chisel3/util/Arbiter.scala 148:31]
  assign io_out_bits_arid = io_in_0_valid ? io_in_0_bits_arid : io_in_1_bits_arid; // @[src/main/scala/chisel3/util/Arbiter.scala 137:15 139:26 141:19]
  assign io_out_bits_araddr = io_in_0_valid ? io_in_0_bits_araddr : io_in_1_bits_araddr; // @[src/main/scala/chisel3/util/Arbiter.scala 137:15 139:26 141:19]
  assign io_out_bits_arlen = io_in_0_valid ? io_in_0_bits_arlen : io_in_1_bits_arlen; // @[src/main/scala/chisel3/util/Arbiter.scala 137:15 139:26 141:19]
  assign io_out_bits_arsize = io_in_0_valid ? io_in_0_bits_arsize : io_in_1_bits_arsize; // @[src/main/scala/chisel3/util/Arbiter.scala 137:15 139:26 141:19]
endmodule
