module BRU(
  input         io_valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_pc, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_inst, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [3:0]  io_uop_ctrl_fuType, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [4:0]  io_uop_ctrl_aluOp, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [3:0]  io_uop_ctrl_bruOp, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [3:0]  io_uop_ctrl_lsuOp, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_ctrl_csrOp, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_ctrl_mulOp, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_ctrl_divOp, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_ctrl_src1Type, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_ctrl_src2Type, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [3:0]  io_uop_ctrl_immType, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_ctrl_rfWen, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_ctrl_memRead, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_ctrl_memWrite, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_ctrl_csrWen, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_ctrl_isBranch, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_ctrl_isJump, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_ctrl_isPriv, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [16:0] io_uop_excp_excpVec, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_imm, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [13:0] io_uop_csrAddress, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_pdInfo_valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_pdInfo_isBr, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_pdInfo_isJal, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_pdInfo_isJalr, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_pdInfo_isCall, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_pdInfo_isRet, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_pdInfo_jumpTarget, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_bpuInfo_pc, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_bpuInfo_fallThrough, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_taken, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_bpuInfo_target, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [1:0]  io_uop_bpuInfo_takenOffset, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_meta_valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_meta_btbHit, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_meta_btbIsJalr, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_meta_btbIsJal, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_meta_btbIsCall, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_meta_btbIsRet, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [1:0]  io_uop_bpuInfo_meta_btbOffset, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [1:0]  io_uop_bpuInfo_meta_phtCounter, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_bpuInfo_meta_rasTop, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_bpuInfo_meta_predTaken, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_uop_bpuInfo_meta_predTarget, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [4:0]  io_uop_ldst, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [4:0]  io_uop_lrs1, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [4:0]  io_uop_lrs2, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [6:0]  io_uop_pdst, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [6:0]  io_uop_prs1, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [6:0]  io_uop_prs2, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [6:0]  io_uop_oldPdst, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_rs1Valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_rs2Valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_rdValid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_snptId_valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_snptId_bits, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [5:0]  io_uop_robIdx_value, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_robIdx_flag, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [5:0]  io_uop_robIdxFull_value, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_robIdxFull_flag, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [3:0]  io_uop_lqIdx_value, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_lqIdx_flag, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [3:0]  io_uop_sqIdx_value, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_sqIdx_flag, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [2:0]  io_uop_issueQueue, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_prs1Busy, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_prs2Busy, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_isSta, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input         io_uop_isStd, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_rs1, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  input  [31:0] io_rs2, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [31:0] io_result, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_bruInfo_valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_bruInfo_bits_doRedirect, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [2:0]  io_bruInfo_bits_snptId, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [5:0]  io_bruInfo_bits_robIdx_value, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_bruInfo_bits_robIdx_flag, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [31:0] io_bruInfo_bits_target, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_isBranch, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_bpuUpdate_valid, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [31:0] io_bpuUpdate_pc, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_bpuUpdate_taken, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [31:0] io_bpuUpdate_target, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [1:0]  io_bpuUpdate_oldPhtCounter, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_bpuUpdate_isJalr, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output        io_bpuUpdate_isJal, // @[src/main/scala/backend/execute/BRU.scala 49:14]
  output [1:0]  io_bpuUpdate_offset // @[src/main/scala/backend/execute/BRU.scala 49:14]
);
  wire  eq = io_rs1 == io_rs2; // @[src/main/scala/backend/execute/BRU.scala 68:18]
  wire  ne = ~eq; // @[src/main/scala/backend/execute/BRU.scala 69:13]
  wire  lt = $signed(io_rs1) < $signed(io_rs2); // @[src/main/scala/backend/execute/BRU.scala 70:25]
  wire  ge = ~lt; // @[src/main/scala/backend/execute/BRU.scala 71:13]
  wire  ltu = io_rs1 < io_rs2; // @[src/main/scala/backend/execute/BRU.scala 72:18]
  wire  geu = ~ltu; // @[src/main/scala/backend/execute/BRU.scala 73:13]
  wire  _branchTaken_T = io_uop_ctrl_bruOp == 4'h1; // @[src/main/scala/backend/execute/BRU.scala 77:9]
  wire  _branchTaken_T_1 = io_uop_ctrl_bruOp == 4'h2; // @[src/main/scala/backend/execute/BRU.scala 78:9]
  wire  _branchTaken_T_2 = io_uop_ctrl_bruOp == 4'h3; // @[src/main/scala/backend/execute/BRU.scala 79:9]
  wire  _branchTaken_T_3 = io_uop_ctrl_bruOp == 4'h4; // @[src/main/scala/backend/execute/BRU.scala 80:9]
  wire  _branchTaken_T_4 = io_uop_ctrl_bruOp == 4'h5; // @[src/main/scala/backend/execute/BRU.scala 81:9]
  wire  _branchTaken_T_5 = io_uop_ctrl_bruOp == 4'h6; // @[src/main/scala/backend/execute/BRU.scala 82:9]
  wire  _branchTaken_T_6 = io_uop_ctrl_bruOp == 4'h7; // @[src/main/scala/backend/execute/BRU.scala 83:9]
  wire  _branchTaken_T_7 = io_uop_ctrl_bruOp == 4'h8; // @[src/main/scala/backend/execute/BRU.scala 84:9]
  wire  _branchTaken_T_8 = io_uop_ctrl_bruOp == 4'h9; // @[src/main/scala/backend/execute/BRU.scala 85:9]
  wire  _branchTaken_T_10 = _branchTaken_T_7 ? ltu : _branchTaken_T_8 & geu; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_11 = _branchTaken_T_6 ? ge : _branchTaken_T_10; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_12 = _branchTaken_T_5 ? lt : _branchTaken_T_11; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_13 = _branchTaken_T_4 ? ne : _branchTaken_T_12; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_14 = _branchTaken_T_3 ? eq : _branchTaken_T_13; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  branchTaken = _branchTaken_T | (_branchTaken_T_1 | (_branchTaken_T_2 | _branchTaken_T_14)); // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [31:0] jirlTarget = io_rs1 + io_uop_imm; // @[src/main/scala/backend/execute/BRU.scala 90:28]
  wire [31:0] branchTarget = io_uop_pc + io_uop_imm; // @[src/main/scala/backend/execute/BRU.scala 91:26]
  wire [31:0] target = _branchTaken_T ? jirlTarget : branchTarget; // @[src/main/scala/backend/execute/BRU.scala 92:25]
  wire [31:0] linkResult = io_uop_pc + 32'h4; // @[src/main/scala/backend/execute/BRU.scala 95:23]
  wire  mispredTaken = ~io_uop_bpuInfo_taken & branchTaken; // @[src/main/scala/backend/execute/BRU.scala 117:35]
  wire  mispredNotTaken = io_uop_bpuInfo_taken & ~branchTaken; // @[src/main/scala/backend/execute/BRU.scala 118:34]
  wire  mispredTarget = io_uop_bpuInfo_taken & branchTaken & io_uop_bpuInfo_target != target; // @[src/main/scala/backend/execute/BRU.scala 119:49]
  wire  mispredict = mispredTaken | mispredNotTaken | mispredTarget; // @[src/main/scala/backend/execute/BRU.scala 120:57]
  wire  _isBranch_T = io_valid & io_isBranch; // @[src/main/scala/backend/execute/BRU.scala 123:27]
  wire  _isBranch_T_1 = ~io_uop_pdInfo_isJal; // @[src/main/scala/backend/execute/BRU.scala 123:45]
  assign io_result = _branchTaken_T_2 | _branchTaken_T ? linkResult : 32'h0; // @[src/main/scala/backend/execute/BRU.scala 96:19]
  assign io_bruInfo_valid = io_valid & io_isBranch & ~io_uop_pdInfo_isJal; // @[src/main/scala/backend/execute/BRU.scala 123:42]
  assign io_bruInfo_bits_doRedirect = _isBranch_T & mispredict & _isBranch_T_1; // @[src/main/scala/backend/execute/BRU.scala 124:60]
  assign io_bruInfo_bits_snptId = io_uop_snptId_bits; // @[src/main/scala/backend/execute/BRU.scala 134:30]
  assign io_bruInfo_bits_robIdx_value = io_uop_robIdxFull_value; // @[src/main/scala/backend/execute/BRU.scala 132:30]
  assign io_bruInfo_bits_robIdx_flag = io_uop_robIdxFull_flag; // @[src/main/scala/backend/execute/BRU.scala 132:30]
  assign io_bruInfo_bits_target = branchTaken ? target : linkResult; // @[src/main/scala/backend/execute/BRU.scala 127:27]
  assign io_isBranch = io_uop_ctrl_bruOp != 4'h0; // @[src/main/scala/backend/execute/BRU.scala 99:21]
  assign io_bpuUpdate_valid = io_valid & io_isBranch & ~io_uop_pdInfo_isJal; // @[src/main/scala/backend/execute/BRU.scala 123:42]
  assign io_bpuUpdate_pc = io_uop_pc; // @[src/main/scala/backend/execute/BRU.scala 147:30]
  assign io_bpuUpdate_taken = _branchTaken_T | (_branchTaken_T_1 | (_branchTaken_T_2 | _branchTaken_T_14)); // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  assign io_bpuUpdate_target = _branchTaken_T ? jirlTarget : branchTarget; // @[src/main/scala/backend/execute/BRU.scala 92:25]
  assign io_bpuUpdate_oldPhtCounter = io_uop_bpuInfo_meta_phtCounter; // @[src/main/scala/backend/execute/BRU.scala 150:30]
  assign io_bpuUpdate_isJalr = io_uop_pdInfo_isJalr; // @[src/main/scala/backend/execute/BRU.scala 151:30]
  assign io_bpuUpdate_isJal = io_uop_pdInfo_isJal; // @[src/main/scala/backend/execute/BRU.scala 152:30]
  assign io_bpuUpdate_offset = io_uop_pc[3:2]; // @[src/main/scala/backend/execute/BRU.scala 155:35]
endmodule
